"""Generate target-state finance workspace tab specifications.

The authoritative menu labels and table columns come from:
    .cursor/billing-accounts-finance.md, sections 9 and 10.

Run:
    python tool/generate_finance_tab_docs.py
    python tool/generate_finance_tab_docs.py --check
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE = REPO_ROOT / ".cursor" / "billing-accounts-finance.md"
OUTPUT_ROOT = REPO_ROOT / ".cursor" / "finance"
GENERATED_MARKER = (
    "<!-- Generated by tool/generate_finance_tab_docs.py. "
    "Edit the source specification or generator, then regenerate. -->"
)

JOURNAL_TABS = [
    "All Journal Entries",
    "General Journal",
    "Sales Journal",
    "Purchase Journal",
    "Cash Receipts Journal",
    "Cash Payments Journal",
    "Adjustment Journal",
    "Payroll Journal",
    "Inventory Journal",
    "Asset Journal",
]

BILLING_TABS = [
    "Overview",
    "Charges",
    "Unbilled Charges",
    "Estimates & Quotations",
    "Packages & Bundles",
    "Invoices",
    "Payments",
    "Payment Allocations",
    "Receipts",
    "Advances & Deposits",
    "Credit Notes",
    "Debit Notes",
    "Refunds",
    "Write-offs",
    "Patient Accounts",
    "Patient Statements",
    "Receivables",
    "Collection Follow-up",
    "Price Lists & Tariffs",
    "Billing Rules",
    "Discount Rules",
    "Tax Rules",
    "Document Templates",
    "Billing Reports",
]

ACCOUNT_GROUPS: list[tuple[tuple[str, ...], tuple[str, ...], list[str]]] = [
    ((), (), ["Overview"]),
    (
        ("General Accounting",),
        ("general-accounting",),
        [
            "Chart of Accounts",
            "General Ledger",
            "Control Accounts",
            "Recurring Entries",
            "Reversing Entries",
        ],
    ),
    (
        ("General Accounting", "Journal Entries"),
        ("general-accounting", "journal-entries"),
        JOURNAL_TABS,
    ),
    (
        ("Purchases & Payables",),
        ("purchases-and-payables",),
        [
            "Suppliers",
            "Purchase Requisitions",
            "Purchase Orders",
            "Goods Received Notes",
            "Supplier Invoices",
            "Supplier Adjustments",
            "Payment Runs",
            "Supplier Payments",
            "Supplier Statements",
            "AP Aging",
            "AP Reconciliation",
        ],
    ),
    (
        ("Expenses",),
        ("expenses",),
        [
            "Expense Entries",
            "Expense Requests",
            "Expense Approvals",
            "Recurring Expenses",
            "Staff Reimbursements",
            "Expense Categories",
            "Expense Analysis",
        ],
    ),
    (
        ("Cash Management",),
        ("cash-management",),
        [
            "Cash Points",
            "Cashier Sessions",
            "Cash Transactions",
            "Cash Transfers",
            "Cash Counts",
            "Session Closures",
            "Cash Variances",
            "Cash Reconciliation",
        ],
    ),
    (
        ("Bank Management",),
        ("bank-management",),
        [
            "Bank Accounts",
            "Bank Transactions",
            "Bank Deposits",
            "Withdrawals & Charges",
            "Bank Transfers",
            "Statement Imports",
            "Matching Workbench",
            "Bank Reconciliations",
        ],
    ),
    (
        ("Fixed Assets",),
        ("fixed-assets",),
        [
            "Asset Register",
            "Asset Categories",
            "Asset Acquisitions",
            "Depreciation Runs",
            "Asset Transfers",
            "Revaluations",
            "Disposals",
            "Asset Ledger",
        ],
    ),
    (
        ("Budgets & Cost Control",),
        ("budgets-and-cost-control",),
        [
            "Annual Budgets",
            "Department Budgets",
            "Project Budgets",
            "Budget Revisions",
            "Commitments",
            "Budget vs Actual",
            "Variance Analysis",
        ],
    ),
    (
        ("Tax & Compliance",),
        ("tax-and-compliance",),
        [
            "Tax Codes & Rates",
            "Tax Transactions",
            "Withholding Tax",
            "Tax Returns",
            "Regulatory Reports",
            "Audit Schedules",
        ],
    ),
    (
        ("Period Close",),
        ("period-close",),
        [
            "Close Checklist",
            "Reconciliation Checklist",
            "Period Adjustments",
            "Reopen Requests",
            "Close History",
            "Year-end Close Runs",
        ],
    ),
    (
        ("Financial Reports",),
        ("financial-reports",),
        [
            "Trial Balance",
            "Income Statement",
            "Balance Sheet",
            "Cash Flow Statement",
            "General Ledger Report",
            "Revenue & Expense Analysis",
            "Department Performance",
            "Cashier & Bank Reports",
            "Consolidated Reports",
        ],
    ),
    (
        ("Setup & Controls",),
        ("setup-and-controls",),
        [
            "Fiscal Years & Periods",
            "Currencies & Exchange Rates",
            "Payment Methods",
            "Document Numbering",
            "Departments & Cost Centres",
            "Posting Rules",
            "Approval Rules",
            "Opening Balances",
            "Integration Mappings",
        ],
    ),
    (
        ("Audit Trail",),
        ("audit-trail",),
        [
            "Transaction History",
            "Approval History",
            "Posting History",
            "Reversals & Voids",
            "Data Exports",
        ],
    ),
]

INSURANCE_TABS = [
    "Overview",
    "Insurance Providers",
    "Corporate Payers",
    "Plans & Products",
    "Contracts",
    "Tariffs & Price Lists",
    "Coverage Rules",
    "Exclusions & Limits",
    "Patient Policies",
    "Members & Dependants",
    "Eligibility Checks",
    "Coverage Balances",
    "Pre-authorizations",
    "Claims",
    "Claim Validations",
    "Claim Batches",
    "Claim Submissions",
    "Adjudications",
    "Denials",
    "Resubmissions & Appeals",
    "Remittance Advice",
    "Insurer Payments",
    "Remittance Allocations",
    "Payer Balances",
    "Claim Reconciliation",
    "Payer Statements",
    "Claims Aging",
    "Collection Follow-up",
    "Disputes",
    "Claim Rules",
    "Required Documents",
    "Denial Codes",
    "Submission Channels",
    "Claim Templates",
    "Insurance Reports",
]

MODULES = {
    "billing": {
        "menu": "Billing",
        "folder": "billing",
        "route": "/billing",
        "api": "/api/v1/billing",
        "entitlement": "billing-payments",
        "read": "billing:read",
        "write": "billing:write",
        "frontend": "frontend/lib/features/billing/presentation/pages/billing_workspace_page.dart",
        "access": "frontend/lib/features/billing/presentation/billing_access.dart",
        "backend": "backend/src/modules/billing/routes/billing.routes.js",
    },
    "accounts": {
        "menu": "Accounts & Finance",
        "folder": "accounts-and-finance",
        "route": "/accounts",
        "api": "/api/v1/accounts",
        "entitlement": "facility-accounts",
        "read": "accounts:read",
        "write": "accounts:write",
        "frontend": "frontend/lib/features/accounts/presentation/pages/accounts_workspace_page.dart",
        "access": "frontend/lib/features/accounts/presentation/accounts_access.dart",
        "backend": "backend/src/modules/accounts-workspace/routes/accounts-workspace.routes.js",
    },
    "claims": {
        "menu": "Insurance & Claims",
        "folder": "insurance-and-claims",
        "route": "/claims",
        "api": "/api/v1/claims-workspace",
        "entitlement": "insurance-claims",
        "read": "claims:read",
        # Current canonical catalog has no claims:write key. Claims mutations reuse
        # billing:write; do not invent a permission without updating both catalogs.
        "write": "billing:write",
        "frontend": "frontend/lib/features/claims/presentation/pages/claims_workspace_page.dart",
        "access": "frontend/lib/features/claims/presentation/claims_access.dart",
        "backend": "backend/src/modules/claims-workspace/routes/claims-workspace.routes.js",
    },
}


@dataclass(frozen=True)
class Tab:
    module_key: str
    group_labels: tuple[str, ...]
    group_slugs: tuple[str, ...]
    label: str
    source_section: str

    @property
    def module(self) -> dict[str, str]:
        return MODULES[self.module_key]

    @property
    def slug(self) -> str:
        return slugify(self.label)

    @property
    def directory(self) -> Path:
        return OUTPUT_ROOT / self.module["folder"] / Path(*self.group_slugs)

    @property
    def path(self) -> Path:
        return self.directory / f"{self.slug}.md"

    @property
    def menu_path(self) -> str:
        return " → ".join((self.module["menu"], *self.group_labels, self.label))


def slugify(value: str) -> str:
    value = value.replace("&", " and ").replace("–", "-").replace("—", "-")
    value = value.replace("/", " and ").replace("'", "")
    value = re.sub(r"[^A-Za-z0-9]+", "-", value)
    return value.strip("-").lower()


def snake_id(value: str) -> str:
    return slugify(value).replace("-", "_")


def all_tabs() -> list[Tab]:
    tabs = [
        Tab("billing", (), (), label, "9.2 / 10.2") for label in BILLING_TABS
    ]
    for group_labels, group_slugs, labels in ACCOUNT_GROUPS:
        tabs.extend(
            Tab("accounts", group_labels, group_slugs, label, "9.3 / 10.3")
            for label in labels
        )
    tabs.extend(
        Tab("claims", (), (), label, "9.4 / 10.4")
        for label in INSURANCE_TABS
    )
    return tabs


def parse_source_columns() -> dict[tuple[str, str], list[str]]:
    if not SOURCE.exists():
        raise FileNotFoundError(f"Source specification not found: {SOURCE}")

    columns: dict[tuple[str, str], list[str]] = {}
    current_module: str | None = None
    bullet = re.compile(r"^- \*\*(.+?)\*\* — (.+)$")

    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        if line.startswith("### 10.2 "):
            current_module = "billing"
            continue
        if line.startswith("### 10.3 "):
            current_module = "accounts"
            continue
        if line.startswith("### 10.4 "):
            current_module = "claims"
            continue
        if line.startswith("## 11."):
            current_module = None
            continue
        if current_module is None:
            continue

        match = bullet.match(line)
        if not match:
            continue
        raw_label, raw_columns = match.groups()
        labels = (
            JOURNAL_TABS
            if current_module == "accounts"
            and raw_label.startswith("All Journal Entries, General Journal,")
            else [raw_label]
        )
        parsed = [item.strip() for item in raw_columns.split(",") if item.strip()]
        for label in labels:
            columns[(current_module, label)] = parsed
    return columns


def parse_source_tabs() -> dict[str, list[str]]:
    """Read permanent leaf tabs from the three Section 9 menu trees."""

    lines = SOURCE.read_text(encoding="utf-8").splitlines()
    heading_to_module = {
        "### 9.2 Billing": "billing",
        "### 9.3 Accounts & Finance": "accounts",
        "### 9.4 Insurance & Claims": "claims",
    }
    nodes: dict[str, list[tuple[int, str]]] = {
        "billing": [],
        "accounts": [],
        "claims": [],
    }
    current_module: str | None = None
    in_code = False

    for line in lines:
        if line in heading_to_module:
            current_module = heading_to_module[line]
            in_code = False
            continue
        if line.startswith("### 9.") and line not in heading_to_module:
            current_module = None
            in_code = False
            continue
        if current_module is None:
            continue
        if line == "```text":
            in_code = True
            continue
        if line == "```":
            in_code = False
            continue
        if not in_code:
            continue
        connector_positions = [
            position
            for connector in ("├── ", "└── ")
            if (position := line.find(connector)) >= 0
        ]
        if not connector_positions:
            continue
        position = min(connector_positions)
        label = line[position + 4 :].strip()
        depth = position // 4 + 1
        nodes[current_module].append((depth, label))

    leaves: dict[str, list[str]] = {}
    for module_key, module_nodes in nodes.items():
        module_leaves: list[str] = []
        for index, (depth, label) in enumerate(module_nodes):
            next_depth = (
                module_nodes[index + 1][0]
                if index + 1 < len(module_nodes)
                else 0
            )
            if next_depth <= depth:
                module_leaves.append(label)
        leaves[module_key] = module_leaves
    return leaves


def markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def relative_link(from_file: Path, target: Path) -> str:
    return Path(os.path.relpath(target, from_file.parent)).as_posix()


def profile_for(tab: Tab) -> str:
    label = tab.label.lower()
    group = " ".join(tab.group_labels).lower()
    if label == "overview":
        return "overview"
    if "audit trail" in group or label in {
        "transaction history",
        "approval history",
        "posting history",
        "reversals & voids",
        "data exports",
    }:
        return "audit"
    if "financial reports" in group or label.endswith("reports"):
        return "report"
    if any(
        token in label
        for token in (
            "reconciliation",
            "matching workbench",
            "checklist",
            "close runs",
            "reopen requests",
        )
    ):
        return "reconciliation"
    if any(
        token in label
        for token in (
            "statement",
            "ledger",
            "aging",
            "analysis",
            "balances",
            "performance",
            "history",
            "trial balance",
            "income statement",
            "balance sheet",
            "cash flow",
            "control accounts",
            "patient accounts",
            "receivables",
            "cash transactions",
            "tax transactions",
        )
    ):
        return "analysis"
    master_tokens = (
        "rules",
        "codes",
        "categories",
        "templates",
        "channels",
        "numbering",
        "methods",
        "currencies",
        "periods",
        "mappings",
        "price lists",
        "tariffs",
        "packages",
        "providers",
        "payers",
        "plans",
        "contracts",
        "policies",
        "members",
        "suppliers",
        "chart of accounts",
        "cash points",
        "bank accounts",
        "asset register",
        "required documents",
        "exclusions",
    )
    if "setup & controls" in group or any(token in label for token in master_tokens):
        return "master"
    return "transaction"


def purpose_for(tab: Tab) -> str:
    profile = profile_for(tab)
    context = tab.group_labels[-1] if tab.group_labels else tab.module["menu"]
    if profile == "overview":
        return (
            f"Provides the {tab.module['menu']} operational summary as a table of "
            "queues, values, exceptions, ownership, service levels, and drill-down "
            "destinations. It is the default tab for the workspace."
        )
    if profile == "report":
        return (
            f"Provides the authoritative {tab.label.lower()} worklist for {context}, "
            "with repeatable filters, drill-down, export, print, and scheduling."
        )
    if profile == "audit":
        return (
            f"Provides an immutable, read-only table for reviewing {tab.label.lower()} "
            "and tracing each event to its source record, actor, permission, and "
            "correlation identifier."
        )
    if profile == "analysis":
        return (
            f"Provides a read-oriented {tab.label.lower()} table for analysis, "
            "reconciliation, drill-down, printing, and export without duplicating "
            "the authoritative source transactions."
        )
    if profile == "reconciliation":
        return (
            f"Coordinates {tab.label.lower()} as an exception-driven worklist. "
            "Users resolve differences, attach evidence, submit review, and finalize "
            "the workflow with complete audit history."
        )
    if profile == "master":
        return (
            f"Maintains the authoritative {tab.label.lower()} records used by "
            f"{context}. The table supports controlled CRUD, versioning, activation, "
            "duplicate prevention, and downstream reference integrity."
        )
    return (
        f"Manages the end-to-end {tab.label.lower()} workflow for {context}. "
        "The table is the authoritative work queue for creation, review, approval, "
        "posting or processing, exception handling, and audit."
    )


def infer_column_type(column: str) -> str:
    name = column.lower()
    if name == "normal balance":
        return "enum"
    if name in {
        "default template",
        "base currency",
        "on hold",
        "mandatory",
        "recoverable",
        "correctable",
        "appeal allowed",
        "auto-post",
        "auto-create",
    }:
        return "boolean"
    if name.endswith(" required"):
        return "boolean"
    if name in {
        "deposits in transit",
        "unpresented payments",
        "bank-only items",
    }:
        return "money"
    if any(token in name for token in ("cost centre", "cost center")):
        return "reference"
    if re.search(r"(^|[\s/])(no\.?|number|code|reference)(\b|$)", name):
        return "reference"
    if any(
        token in name
        for token in (
            "account no",
            "policy no",
            "claim no",
            "invoice no",
            "entry no",
            "document no",
        )
    ):
        return "reference"
    if "date/time" in name or name.endswith(" at") or "timestamp" in name:
        return "datetime"
    if any(
        token in name
        for token in (
            "date",
            "valid from",
            "valid until",
            "service from",
            "service to",
            "period from",
            "period to",
            "effective from",
            "effective to",
        )
    ):
        return "date"
    if name == "currency" or name.endswith(" currency"):
        return "currency"
    if "percentage" in name or name.endswith(" rate") or name in {
        "rate",
        "burn rate",
        "exchange rate",
    }:
        return "percentage"
    if re.search(r"\b\d+[–-]\d+\s+days\b", name) or name in {
        "current",
        "over 90 days",
    }:
        return "money"
    if any(
        token in name
        for token in (
            "amount",
            "balance",
            "price",
            "cost",
            "debit",
            "credit",
            "tax",
            "budget",
            "proceeds",
            "margin",
            "revenue",
            "expense",
            "cash",
            "value",
            "subtotal",
            "total",
            "discount",
            "difference",
            "share",
            "withheld",
            "deduction",
            "limit",
            "float",
            "taxable",
            "actual",
            "commitment",
        )
    ):
        return "money"
    if re.search(r"\b(count|quantity|days|age|level|priority)\b", name):
        return "number"
    if any(token in name for token in ("status", "type", "method", "category")):
        return "status" if "status" in name else "enum"
    if name.endswith(" name") or name in {"name", "description", "reason", "notes"}:
        return "text"
    if any(
        token in name
        for token in (
            "required",
            "allowed",
            "active",
            "auto-",
            "matched",
            "attached",
        )
    ):
        return "boolean"
    if any(token in name for token in ("account", "policy", "claim", "invoice", "entry", "document")):
        return "reference"
    return "text"


def column_behavior(column: str, column_type: str) -> str:
    name = column.lower()
    if column_type == "money":
        return "Right-aligned; currency precision; subtotal when meaningful."
    if column_type == "percentage":
        return "Right-aligned percentage with configured precision."
    if column_type in {"date", "datetime"}:
        return "Localized display; API remains ISO-8601; date filter enabled."
    if column_type == "status":
        return "Localized `AppWorkspaceStatusBadge`; never expose raw enum text."
    if "status" in name:
        return "Localized status badge; raw backend enum is not displayed."
    if column_type == "reference":
        return "Human-friendly reference; opens the authoritative detail."
    if any(token in name for token in ("name", "patient", "supplier", "payer")):
        return "Searchable display value; opens permitted source context."
    if column_type == "boolean":
        return "Localized Yes/No or active/inactive chip."
    if any(token in name for token in ("description", "reason", "notes", "message")):
        return "Wrap or truncate with tooltip; full value in detail dialog."
    return "Localized text; null values render as an em dash."


def is_sortable(column: str) -> bool:
    return not any(
        token in column.lower()
        for token in ("description", "notes", "message", "available filters")
    )


def is_filterable(column: str) -> bool:
    return any(
        token in column.lower()
        for token in (
            "date",
            "status",
            "type",
            "name",
            "patient",
            "supplier",
            "payer",
            "department",
            "facility",
            "currency",
            "category",
            "method",
            "account",
            "reference",
            "assigned",
            "owner",
        )
    )


def table_columns_markdown(columns: list[str]) -> str:
    rows = [
        "| # | Column ID | Label | Type | Default | Sortable | Filterable | Display behavior |",
        "|---:|---|---|---|:---:|:---:|:---:|---|",
    ]
    for index, column in enumerate(columns, start=1):
        column_type = infer_column_type(column)
        default = (
            "Yes"
            if index <= 10
            or any(token in column.lower() for token in ("status", "reference", "balance"))
            else "Optional"
        )
        rows.append(
            "| "
            + " | ".join(
                [
                    str(index),
                    f"`{snake_id(column)}`",
                    markdown_escape(column),
                    column_type,
                    default,
                    "Yes" if is_sortable(column) else "No",
                    "Yes" if is_filterable(column) else "No",
                    markdown_escape(column_behavior(column, column_type)),
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def filters_for(columns: list[str]) -> list[tuple[str, str, str, str]]:
    lower_columns = " ".join(columns).lower()
    filters: list[tuple[str, str, str, str]] = [
        ("Search", "server text search", "blank", "Matches human-friendly reference and permitted display fields."),
        ("Status", "multi-select", "open/active", "Only statuses applicable to this tab are offered."),
    ]
    if any(token in lower_columns for token in ("date", "period", " at")):
        filters.append(("Date/period", "date range or fiscal period", "current period", "Uses facility timezone and inclusive boundaries."))
    if "facility" in lower_columns:
        filters.append(("Facility", "multi-select", "current facility", "Restricted by tenant/facility ABAC scope."))
    if any(token in lower_columns for token in ("department", "cost centre")):
        filters.append(("Department / cost centre", "hierarchical multi-select", "all allowed", "Values come from controlled reference data."))
    if any(token in lower_columns for token in ("patient", "supplier", "payer", "customer", "payee")):
        filters.append(("Party", "async search-select", "all", "Searches only parties visible in the user's ABAC scope."))
    if "currency" in lower_columns:
        filters.append(("Currency", "select", "base currency", "Original-currency values remain available."))
    if any(token in lower_columns for token in ("amount", "balance", "price", "cost")):
        filters.append(("Amount range", "minimum / maximum money", "blank", "Requires currency when mixed-currency rows are present."))
    if any(token in lower_columns for token in ("assigned", "owner", "cashier", "prepared by")):
        filters.append(("Owner / assigned user", "user search-select", "all", "Restricted to permitted facility staff."))
    return filters[:9]


def permission_set(tab: Tab) -> dict[str, str]:
    read = tab.module["read"]
    write = tab.module["write"]
    return {
        "read": f"`{read}` ∩ `{tab.module['entitlement']}`",
        "write": f"`{write}` ∩ `{tab.module['entitlement']}`",
        "approve": f"`{write}` ∩ `financial:approve` ∩ `{tab.module['entitlement']}`",
        "export": f"`{read}` ∩ `evidence:export` ∩ `{tab.module['entitlement']}`",
    }


def context_actions(tab: Tab) -> list[tuple[str, str, str, str]]:
    label = tab.label.lower()
    permissions = permission_set(tab)
    actions: list[tuple[str, str, str, str]] = []

    mappings = [
        (("unbilled charges",), ("Generate invoices", "selected eligible rows", "Creates draft invoices and refreshes Billing counts.")),
        (("charges",), ("Add charge", "write permitted", "Opens charge mutation dialog.")),
        (("estimates",), ("New estimate", "write permitted", "Creates a draft estimate.")),
        (("packages",), ("New package", "write permitted", "Opens package editor with included-services table.")),
        (("invoices",), ("New invoice", "write permitted", "Opens invoice header and line-item dialog.")),
        (("payments",), ("Record payment", "write permitted", "Opens payment dialog and returns the created row.")),
        (("allocations",), ("Allocate", "unallocated value exists", "Opens allocation workbench.")),
        (("refund",), ("Request refund", "refundable balance exists", "Creates a maker-checker refund request.")),
        (("write-off",), ("Request write-off", "open eligible balance", "Creates an approval request.")),
        (("patient accounts",), ("Open statement", "account selected", "Opens the filtered Patient Statements tab.")),
        (("receivables",), ("Assign collector", "open balances selected", "Assigns collection ownership without changing source invoices.")),
        (("journal",), ("New journal entry", "period open", "Opens balanced journal-entry dialog.")),
        (("purchase requisitions",), ("New requisition", "write permitted", "Opens requisition and line-item dialog.")),
        (("purchase orders",), ("New purchase order", "write permitted", "Opens PO header and line-item dialog.")),
        (("goods received",), ("Record goods receipt", "approved PO has open quantity", "Opens receipt and inspection dialog.")),
        (("supplier invoices",), ("Record supplier invoice", "write permitted", "Opens three-way-match dialog.")),
        (("payment runs",), ("Create payment run", "approved due invoices exist", "Builds a proposed supplier batch.")),
        (("expense",), ("New expense", "write permitted", "Opens expense request/entry dialog.")),
        (("cash counts",), ("Start cash count", "active session selected", "Opens denomination-count dialog.")),
        (("session closures",), ("Close session", "session is reconcilable", "Opens closure review dialog.")),
        (("bank deposits",), ("Record deposit", "write permitted", "Links deposit to cashier sessions.")),
        (("statement imports",), ("Import statement", "supported bank format", "Opens file validation wizard.")),
        (("depreciation runs",), ("Calculate depreciation", "period open", "Creates a preview run without posting.")),
        (("budget",), ("New budget record", "write permitted", "Opens budget header and lines editor.")),
        (("tax returns",), ("Prepare return", "tax period open", "Builds a return from posted tax transactions.")),
        (("pre-authorizations",), ("Request pre-authorization", "eligible policy selected", "Opens authorization request dialog.")),
        (("eligibility checks",), ("Check eligibility", "member and service context supplied", "Runs payer eligibility and records the response.")),
        (("claims",), ("Generate claim", "eligible unclaimed charges exist", "Creates a draft claim with claim items.")),
        (("claim validations",), ("Run validation", "draft claims selected", "Executes configured claim rules and refreshes errors.")),
        (("claim batches",), ("Create batch", "validated claims selected", "Groups claims for submission.")),
        (("claim submissions",), ("Submit selected", "claims validated", "Sends via the configured submission channel.")),
        (("adjudications",), ("Record adjudication", "payer response available", "Captures item-level payer decisions.")),
        (("denials",), ("Assign denial", "denial is open", "Assigns owner and response deadline.")),
        (("appeals",), ("Create appeal/resubmission", "denial is appealable", "Opens appeal evidence dialog.")),
        (("remittance advice",), ("Import remittance", "supported payer format", "Validates and stages remittance lines.")),
    ]
    for tokens, (name, condition, result) in mappings:
        if any(token in label for token in tokens):
            actions.append((name, permissions["write"], condition, result))
            break
    return actions


def toolbar_actions(tab: Tab) -> list[tuple[str, str, str, str]]:
    profile = profile_for(tab)
    permissions = permission_set(tab)
    actions = context_actions(tab)
    if profile == "master" and not actions:
        actions.append(
            (
                "New record",
                permissions["write"],
                "write permitted",
                f"Opens the {tab.label} create dialog.",
            )
        )
    elif profile == "transaction" and not actions:
        actions.append(
            (
                "New record",
                permissions["write"],
                "write permitted and source prerequisites met",
                f"Opens the {tab.label} mutation dialog.",
            )
        )
    elif profile == "reconciliation":
        actions.extend(
            [
                ("Start work", permissions["write"], "eligible period/source selected", "Creates a draft work item."),
                ("Auto-match", permissions["write"], "unmatched rows exist", "Applies deterministic matching rules and shows exceptions."),
            ]
        )
    elif profile == "report":
        actions.extend(
            [
                ("Run report", permissions["read"], "filters valid", "Refreshes report rows and totals."),
                ("Schedule", permissions["write"], "scheduling supported", "Opens report schedule dialog."),
            ]
        )
    elif profile == "analysis":
        actions.append(("Save view", permissions["read"], "filters changed", "Stores a named personal view."))

    actions.extend(
        [
            ("Refresh", permissions["read"], "always", "Targeted refresh of rows and count badge."),
            ("Filters", permissions["read"], "always", "Opens advanced filter group."),
            ("Columns", permissions["read"], "always", "Opens column visibility and ordering settings."),
            ("Export", permissions["export"], "rows visible", "Exports matching rows and records an audit event."),
            ("Print", permissions["export"], "rows visible", "Opens print preview using matching rows."),
        ]
    )
    return actions


def row_actions(tab: Tab) -> list[tuple[str, str, str, str]]:
    profile = profile_for(tab)
    permissions = permission_set(tab)
    actions = [
        ("View", permissions["read"], "always", "Opens a detail `AppDialog` using the human-friendly reference.")
    ]
    if profile == "master":
        actions.extend(
            [
                ("Edit", permissions["write"], "record active/draft and version current", "Opens prefilled edit dialog."),
                ("Clone", permissions["write"], "record clonable", "Creates an unsaved copy with a new reference."),
                ("Activate / deactivate", permissions["write"], "transition allowed", "Requires confirmation and refreshes dependants."),
                ("Archive / restore", permissions["write"], "not referenced by a blocking workflow", "Soft archive only; never hard-delete referenced data."),
            ]
        )
    elif profile == "transaction":
        actions.extend(
            [
                ("Edit draft", permissions["write"], "status is draft/returned", "Opens mutation dialog with optimistic version."),
                ("Submit", permissions["write"], "validation passes", "Moves record to approval/review queue."),
                ("Approve / reject", permissions["approve"], "pending approval and maker-checker satisfied", "Records decision and reason."),
                ("Post / process", permissions["write"], "approved and period/workflow open", "Runs atomic mutation and refreshes linked modules."),
                ("Reverse / void", permissions["approve"], "posted/processed and policy allows", "Reason required; creates linked reversal, never deletes history."),
                ("Print", permissions["export"], "formal document available", "Opens document-template preview."),
            ]
        )
    elif profile == "reconciliation":
        actions.extend(
            [
                ("Open workbench", permissions["write"], "record not finalized", "Opens matches, exceptions, evidence, and notes."),
                ("Resolve exception", permissions["write"], "exception selected", "Captures resolution and supporting reference."),
                ("Submit / approve", permissions["approve"], "all blocking exceptions resolved", "Completes maker-checker review."),
                ("Finalize / reopen", permissions["approve"], "transition permitted", "Finalizes or creates an audited reopen request."),
            ]
        )
    elif profile in {"analysis", "report"}:
        actions.extend(
            [
                ("Drill down", permissions["read"], "source dimension available", "Opens the authoritative filtered source tab."),
                ("Export row/detail", permissions["export"], "row visible", "Exports the selected breakdown."),
            ]
        )
    elif profile == "audit":
        actions.extend(
            [
                ("Inspect event", permissions["read"], "always", "Shows immutable before/after, actor, scope, and correlation data."),
                ("Open source", permissions["read"], "source still visible", "Opens authoritative record without duplicating it."),
            ]
        )
    else:
        actions.append(("Open queue", permissions["read"], "metric has a destination", "Opens the matching filtered tab."))
    return actions


def bulk_actions(tab: Tab) -> list[tuple[str, str, str]]:
    profile = profile_for(tab)
    permissions = permission_set(tab)
    if profile == "master":
        return [
            ("Activate / deactivate selected", permissions["write"], "Only compatible, unblocked records are changed."),
            ("Archive selected", permissions["write"], "Soft archive; partial failures return per-row reasons."),
            ("Export selected", permissions["export"], "Exports selected rows in visible-column order."),
        ]
    if profile == "transaction":
        return [
            ("Submit selected", permissions["write"], "Only valid draft rows are submitted."),
            ("Approve selected", permissions["approve"], "Maker-checker and homogeneous status required."),
            ("Post/process selected", permissions["write"], "Atomic per record; failures do not hide successful rows."),
            ("Export selected", permissions["export"], "Audit event records filters and row count."),
        ]
    if profile == "reconciliation":
        return [
            ("Assign selected", permissions["write"], "Assigns compatible exceptions to one owner."),
            ("Resolve selected", permissions["write"], "Requires one resolution code and note."),
            ("Export selected", permissions["export"], "Includes reconciliation references and evidence counts."),
        ]
    return [
        ("Export selected", permissions["export"], "Exports only rows in the user's current ABAC scope.")
    ]


def status_rows(tab: Tab) -> list[tuple[str, str, str]]:
    profile = profile_for(tab)
    label = tab.label.lower()
    if profile in {"overview", "analysis", "audit"}:
        return [("Read-only", "Derived from authoritative source state.", "No direct transition.")]
    if profile == "report":
        return [
            ("Queued", "Generation requested.", "→ Running / Cancelled"),
            ("Running", "Rows are being built.", "→ Ready / Failed"),
            ("Ready", "Output available.", "→ Expired"),
            ("Failed", "Generation failed with safe error code.", "→ Queued"),
        ]
    if profile == "master":
        return [
            ("Draft", "Not available to downstream workflows.", "→ Active / Archived"),
            ("Active", "Selectable by permitted workflows.", "→ Inactive / Archived"),
            ("Inactive", "Retained but not selectable for new work.", "→ Active / Archived"),
            ("Archived", "Soft-deleted historical record.", "→ Active when restore is safe"),
        ]
    if profile == "reconciliation":
        return [
            ("Draft", "Work item created.", "→ In progress / Abandoned"),
            ("In progress", "Matching and exception resolution underway.", "→ Submitted"),
            ("Submitted", "Awaiting independent review.", "→ Approved / Returned"),
            ("Approved", "Review complete.", "→ Finalized"),
            ("Finalized", "Locked result.", "→ Reopen requested"),
            ("Reopened", "Audited correction window active.", "→ Finalized"),
        ]
    if tab.module_key == "claims" or "claim" in label:
        return [
            ("Draft", "Claim-related record is editable.", "→ Validated / Cancelled"),
            ("Validated", "Blocking validation passed.", "→ Submitted"),
            ("Submitted", "Sent to payer.", "→ In review / Rejected"),
            ("In review", "Awaiting payer decision.", "→ Approved / Partially approved / Denied"),
            ("Approved / Partially approved", "Adjudicated amount accepted.", "→ Paid / Appealed"),
            ("Denied", "Payer rejected all or part.", "→ Resubmitted / Appealed / Closed"),
            ("Paid / Closed", "Settlement complete.", "Terminal except audited reopening"),
        ]
    if "invoice" in label:
        return [
            ("Draft", "Editable invoice.", "→ Issued / Cancelled"),
            ("Issued", "Receivable recognized.", "→ Partially paid / Paid / Overdue"),
            ("Partially paid", "Some balance allocated.", "→ Paid / Overdue"),
            ("Paid", "Balance fully settled.", "Terminal except adjustment/refund"),
            ("Overdue", "Due date passed with balance.", "→ Partially paid / Paid / Written off"),
            ("Cancelled / Written off", "Closed by controlled adjustment.", "Terminal"),
        ]
    return [
        ("Draft", "Editable and unposted.", "→ Submitted / Cancelled"),
        ("Submitted", "Awaiting review.", "→ Approved / Rejected / Returned"),
        ("Approved", "Authorized for processing/posting.", "→ Posted / Processed"),
        ("Posted / Processed", "Authoritative financial effect recorded.", "→ Reversed / Voided"),
        ("Reversed / Voided", "Original retained with linked correction.", "Terminal"),
    ]


def detail_sections(tab: Tab) -> list[tuple[str, str, str]]:
    label = tab.label.lower()
    if "invoice" in label:
        return [
            ("Summary", "Header, party, payer, dates, totals, status", "Read-only header with quick actions."),
            ("Line items", "Service/item, quantity, price, discount, tax, line total", "Nested `AppListTable`; editable only in draft."),
            ("Payments & allocations", "Payment ref, allocation date, amount, remaining balance", "Links to Billing payment tabs."),
            ("Adjustments", "Credit/debit notes, refunds, write-offs", "Immutable links after posting."),
            ("Documents & audit", "Attachments, approvals, postings, print history", "Collapsible detail panels."),
        ]
    if "payment" in label or "remittance" in label or "receipt" in label:
        return [
            ("Summary", "Method, payer/payee, value date, amount, currency, status", "Read-only header."),
            ("Allocations", "Source reference, target invoice/claim, amount, remaining", "Nested table with allocation action."),
            ("Settlement", "Cash point/bank, external reference, reconciliation", "Cross-links to treasury."),
            ("Documents & audit", "Receipt/remittance files, approvals, reversals", "Immutable event history."),
        ]
    if "claim" in label or "adjudication" in label or "denial" in label:
        return [
            ("Claim summary", "Member, policy, payer, encounter, amounts, status", "Patient and payer header."),
            ("Claim items", "Service, diagnosis, submitted/approved/denied amounts", "Nested `AppListTable`."),
            ("Validations & documents", "Rule results, required evidence, submission readiness", "Blocking errors highlighted."),
            ("Adjudication, denial & appeal", "Decision codes, reasons, deadlines, responses", "Stage-aware quick actions."),
            ("Submission & audit history", "Batches, channel responses, actor timeline", "Immutable timeline table."),
        ]
    if "journal" in label or "ledger" in label:
        return [
            ("Entry/account summary", "Period, journal/account, source, totals, status", "Header and posting actions."),
            ("Journal lines", "Account, description, department, debit, credit, currency", "Nested balanced line table."),
            ("Source documents", "Owning module and human-friendly references", "Cross-module links."),
            ("Approval & posting history", "Maker, checker, posting, reversal", "Immutable audit table."),
        ]
    if any(token in label for token in ("purchase", "goods received", "supplier")):
        return [
            ("Summary", "Supplier, dates, terms, totals, status", "Header and procurement quick actions."),
            ("Items", "Item, quantity, unit cost, tax, received/invoiced balance", "Nested line table."),
            ("Document chain", "Requisition, PO, GRN, invoice, payment", "Traceable source links."),
            ("Approvals & audit", "Decisions, matching exceptions, attachments", "Immutable workflow history."),
        ]
    if any(token in label for token in ("asset", "depreciation", "revaluation", "disposal")):
        return [
            ("Asset summary", "Identity, category, location, custodian, value", "Header with lifecycle status."),
            ("Valuation history", "Acquisition, depreciation, revaluation, disposal", "Nested financial timeline."),
            ("Transfers & documents", "Location/custodian changes and evidence", "Cross-linked records."),
            ("Posting & audit", "Journal entries, approvals, actor history", "Immutable history."),
        ]
    if any(token in label for token in ("cash", "bank", "reconciliation", "matching")):
        return [
            ("Summary", "Account/point/session, period, balances, status", "Header and reconcile quick actions."),
            ("Transactions", "Date, reference, counterparty, debit/credit, match state", "Paginated nested table."),
            ("Matches & exceptions", "System row, statement row, difference, resolution", "Exception workbench."),
            ("Evidence & audit", "Counts, statements, approvals, finalization", "Immutable history."),
        ]
    return [
        ("Summary", "Key table columns and current workflow status", "Uses `AppWorkspaceDetailPanel`."),
        ("Related records", "Authoritative cross-module references", "Links open owning-module tabs."),
        ("Attachments", "Document type, file name, uploaded by/at", "Permission-gated download/preview."),
        ("Activity & audit", "Event, actor, timestamp, reason, correlation ID", "Immutable timeline table."),
    ]


def editable_form_fields(tab: Tab, columns: list[str], profile: str) -> list[str]:
    if profile in {"overview", "analysis", "report", "audit"}:
        return []
    blocked_fragments = (
        "status",
        "created",
        "updated",
        "approved by",
        "approved at",
        "posted by",
        "posted at",
        "running",
        "available",
        "remaining",
        "variance",
        "last ",
        "journal entry",
        "paid amount",
        "allocated amount",
        "unallocated amount",
        "current balance",
        "opening balance",
        "closing balance",
        "total outstanding",
        "accumulated",
        "net book value",
        "row count",
        "exception count",
        "issued by",
        "received by",
        "processed by",
        "prepared by",
        "reviewed by",
        "requested by",
    )
    calculated_exact = {
        "subtotal",
        "total",
        "grand total",
        "tax",
        "difference",
        "current",
        "1–30 days",
        "31–60 days",
        "61–90 days",
        "over 90 days",
    }
    candidates: list[str] = []
    for index, column in enumerate(columns):
        lower = column.lower()
        if any(token in lower for token in blocked_fragments):
            continue
        if re.search(r"\b(count|age)\b", lower):
            continue
        if lower in calculated_exact or lower.startswith("total "):
            continue
        if profile in {"transaction", "reconciliation"} and any(
            token in lower
            for token in (
                "balance",
                "aging",
            )
        ):
            continue
        if tab.module_key == "claims" and profile == "transaction" and any(
            token in lower
            for token in (
                "submitted amount",
                "approved amount",
                "rejected amount",
                "paid amount",
                "outstanding amount",
                "patient share",
            )
        ):
            continue
        if (
            profile in {"transaction", "reconciliation"}
            and index == 0
            and re.search(r"\b(no\.?|number|reference)\b", lower)
        ):
            continue
        candidates.append(column)
    return candidates[:10]


def validation_rules(tab: Tab) -> list[str]:
    label = tab.label.lower()
    rules = [
        "Client and server validate required values, lengths, formats, date ordering, and optimistic record version.",
        "Backend revalidates tenant, facility, department, ownership, entitlement, permission, and current workflow state.",
        "Public requests and responses use human-friendly identifiers; raw database IDs never appear.",
        "Duplicate submission is prevented with an idempotency key for financial mutations.",
    ]
    if any(token in label for token in ("journal", "trial balance")):
        rules.append("Journal debits and credits must balance in every currency before approval or posting.")
    if any(token in label for token in ("allocation", "payment", "refund", "write-off")):
        rules.append("Amounts must be positive and cannot exceed the eligible, unallocated, refundable, or open balance.")
    if any(token in label for token in ("invoice", "charge", "price", "tariff", "tax")):
        rules.append("Line totals, discounts, taxes, payer responsibility, and document totals are recalculated server-side.")
    if tab.module_key == "accounts":
        rules.append("Posting, close, reversal, and adjustment actions are blocked when the fiscal period is locked.")
    if tab.module_key == "claims":
        rules.append("Eligibility, coverage, authorization, required documents, deadlines, and payer rules are rechecked server-side.")
    return rules


def render_action_table(
    rows: list[tuple[str, str, str, str]], heading: str
) -> str:
    output = [
        f"### {heading}",
        "",
        "| Button | Permission | Enabled when | Result |",
        "|---|---|---|---|",
    ]
    output.extend(
        f"| {markdown_escape(name)} | {permission} | {markdown_escape(condition)} | {markdown_escape(result)} |"
        for name, permission, condition, result in rows
    )
    return "\n".join(output)


def render_tab(tab: Tab, columns: list[str]) -> str:
    permissions = permission_set(tab)
    profile = profile_for(tab)
    source_link = relative_link(tab.path, SOURCE)
    shared_link = relative_link(tab.path, OUTPUT_ROOT / "_shared")
    path_parts = [tab.module["menu"], *tab.group_labels, tab.label]
    title_path = " → ".join(path_parts)
    canonical_url = f"{tab.module['route']}?section={tab.slug}"
    list_endpoint = f"{tab.module['api']}/work-items?section={tab.slug}"
    detail_endpoint = f"{tab.module['api']}/{tab.slug}/{{human_friendly_id}}"
    mutable = profile in {"master", "transaction", "reconciliation"}
    approvable = profile in {"transaction", "reconciliation"}
    create_supported = "Yes" if mutable else "No"
    update_supported = "Yes" if mutable else "No"
    delete_supported = "Conditional" if mutable else "No"
    approve_supported = "Yes" if approvable else "N/A"
    process_supported = "Yes" if approvable else "N/A"
    delete_rule = (
        "Master data uses soft archive; draft-only administrative delete may be "
        "allowed. Posted financial records are never hard-deleted."
        if mutable
        else "Read-only/derived tabs do not delete source records."
    )
    approval_rule = (
        "Maker-checker: creator cannot approve when segregation rules require independence."
        if approvable
        else "Not applicable; approval remains on the authoritative source workflow."
    )
    process_rule = (
        "Atomic service transaction; period, entitlement, permission, and source-state checks are repeated server-side."
        if approvable
        else "Not applicable; this tab reads authoritative posted/derived data."
    )
    api_operations: list[tuple[str, str, str]] = [
        (
            "List",
            f"GET {list_endpoint}",
            "`page`, `limit`, `sort_by`, `order`, search, filters; paginated `data` + `meta`.",
        )
    ]
    if profile != "overview":
        api_operations.append(
            (
                "Detail / drill-down",
                f"GET {detail_endpoint}",
                "Uses public human-friendly identifier or a stable report row key.",
            )
        )
    if profile == "master":
        api_operations.extend(
            [
                ("Create", f"POST {tab.module['api']}/{tab.slug}", "Validates duplicate/similarity rules and assigns version metadata."),
                ("Update", f"PUT {detail_endpoint}", "Optimistic `version`; `409` returns current record metadata."),
                ("Activate/archive", f"POST {detail_endpoint}/{{action}}", "Uses activate, deactivate, archive, or restore with an audit reason."),
            ]
        )
    elif profile == "transaction":
        api_operations.extend(
            [
                ("Create", f"POST {tab.module['api']}/{tab.slug}", "Idempotency key required for financial mutations."),
                ("Update draft", f"PUT {detail_endpoint}", "Optimistic `version`; only editable workflow states."),
                ("Workflow action", f"POST {detail_endpoint}/{{action}}", "Submit, approve, post/process, allocate, reverse, or void; reason required where applicable."),
            ]
        )
    elif profile == "reconciliation":
        api_operations.extend(
            [
                ("Start", f"POST {tab.module['api']}/{tab.slug}", "Creates an idempotent draft reconciliation/work item."),
                ("Update work item", f"PUT {detail_endpoint}", "Persists matches, exceptions, evidence, notes, and version."),
                ("Workflow action", f"POST {detail_endpoint}/{{action}}", "Submit, approve, finalize, or request reopening with an audit reason."),
            ]
        )
    elif profile == "report":
        api_operations.extend(
            [
                ("Run report", f"POST {tab.module['api']}/reports/{tab.slug}/run", "Returns job/result metadata; no source transaction mutation."),
                ("Schedule", f"POST {tab.module['api']}/reports/{tab.slug}/schedules", "Creates or updates a permission-scoped delivery schedule."),
            ]
        )
    api_rows = "\n".join(
        f"| {operation} | `{path}` | {notes} |"
        for operation, path, notes in api_operations
    )

    filter_rows = "\n".join(
        f"| {markdown_escape(name)} | {kind} | {markdown_escape(default)} | {markdown_escape(notes)} |"
        for name, kind, default, notes in filters_for(columns)
    )
    bulk_rows = "\n".join(
        f"| {markdown_escape(name)} | {permission} | {markdown_escape(behavior)} |"
        for name, permission, behavior in bulk_actions(tab)
    )
    status_table = "\n".join(
        f"| {markdown_escape(status)} | {markdown_escape(meaning)} | {markdown_escape(transitions)} |"
        for status, meaning, transitions in status_rows(tab)
    )
    detail_table = "\n".join(
        f"| {markdown_escape(name)} | {markdown_escape(content)} | {markdown_escape(behavior)} |"
        for name, content, behavior in detail_sections(tab)
    )
    form_fields = editable_form_fields(tab, columns, profile)
    if form_fields:
        form_rows = []
        for field in form_fields:
            field_type = infer_column_type(field)
            validation = {
                "money": "Non-negative; currency required; configured precision.",
                "date": "Valid ISO date; obeys start/end and period rules.",
                "datetime": "Valid ISO timestamp; converted using facility timezone.",
                "percentage": "Within configured percentage range.",
                "reference": "Existing visible human-friendly reference.",
                "enum": "Value from controlled localized options.",
                "boolean": "Explicit true/false selection.",
            }.get(field_type, "Trimmed; length and domain constraints enforced.")
            form_rows.append(
                f"| {markdown_escape(field)} | {field_type} | "
                f"{'Yes' if len(form_rows) < 4 else 'Conditional'} | "
                f"{markdown_escape(validation)} |"
            )
        form_block = "\n".join(
            [
                "| Field | Control/type | Required | Validation |",
                "|---|---|:---:|---|",
                *form_rows,
                "",
                "- The backend assigns the human-friendly reference and initial status.",
                "- Add/remove line-item controls use a nested `AppListTable` where the record has lines.",
                "- Save draft and submit are separate actions; closing with unsaved changes requires confirmation.",
            ]
        )
    else:
        form_block = (
            "This tab is read-oriented and has no direct create/edit form. "
            "Users change filters, drill into source records, save views, print, or export."
        )

    validation = "\n".join(f"- {rule}" for rule in validation_rules(tab))
    frontmatter_submenu = " → ".join(tab.group_labels)
    claims_permission_note = (
        "\n> Claims currently reuses `billing:write` for mutations because the canonical "
        "permission catalog has no `claims:write`. Add a dedicated key to both backend "
        "and frontend catalogs before changing this contract.\n"
        if tab.module_key == "claims"
        else ""
    )
    parent_behavior = (
        "Accounts category labels expand/collapse; this leaf submenu opens the tab"
        if tab.module_key == "accounts"
        else f"The {tab.module['menu']} menu opens this flat workspace tab"
    )

    return f"""{GENERATED_MARKER}
---
menu: "{tab.module['menu']}"
submenu: "{frontmatter_submenu}"
tab: "{tab.label}"
tab_slug: "{tab.slug}"
module_key: "{tab.module_key}"
route: "{canonical_url}"
entitlement: "{tab.module['entitlement']}"
source_sections: "{tab.source_section}"
implementation_status: "target-refactor"
---

# {tab.label}

## Purpose

{purpose_for(tab)}

This is a target-state specification. Existing Billing, Accounts, or Claims code may implement only a subset; the source-of-truth document and this specification define the intended refactor.

## Navigation and workspace placement

- **Menu path:** `{title_path}`
- **Canonical URL:** `{canonical_url}`
- **Tab kind:** permanent `{profile}` table/worklist
- **Reopen behavior:** focus the existing tab and preserve search, filters, sort, page, and selected columns
- **Parent behavior:** {parent_behavior}
- **Source:** [{SOURCE.name}]({source_link}) §§{tab.source_section}

## Pharmacy-guided UI implementation

Follow the `/pharmacy` workspace conventions:

- `AsyncStateScaffold` → `ResponsivePage` → `AppWorkspace`
- `AppTabStrip` for Billing and Insurance tabs; Accounts leaf submenu selection opens the same tab model
- `AppListTable` for the primary table, server pagination, saved columns, export, and print
- Row click opens `showAppDialog` / `AppDialog`; sections use `AppWorkspaceDetailPanel`
- Mutations use `AppWorkspaceMutationDialog` or `AppDialog`, not permanent create/edit tabs
- `AppAccessActionGate` hides unauthorized buttons; unavailable menu/tabs are omitted
- `syncWorkspaceLocation` keeps the section slug, filters, and deep links synchronized
- Active tab count comes from the filtered server total; inactive badge counts come from the workspace summary

See [{shared_link}/workspace-pattern.md]({shared_link}/workspace-pattern.md) for exact Pharmacy references and the target extraction pattern.

## Primary table columns

The baseline table columns and behavior in [{shared_link}/table-contract.md]({shared_link}/table-contract.md) are additive to the columns below.

{table_columns_markdown(columns)}

### Column defaults

- Freeze the first identifying reference and primary party/name columns.
- Default sort uses the most relevant business date descending, then human-friendly reference descending.
- Monetary totals are computed for the filtered result on the server, not only the visible page.
- Optional columns remain available in the column picker and exports.
- PHI and financial amounts are masked or omitted when ABAC scope does not permit them.

## Filters

| Filter | Control | Default | Behavior |
|---|---|---|---|
{filter_rows}

{render_action_table(toolbar_actions(tab), "Toolbar buttons")}

{render_action_table(row_actions(tab), "Row buttons")}

### Bulk buttons

| Button | Permission | Behavior |
|---|---|---|
{bulk_rows}

## CRUD and workflow contract

| Capability | Supported | Rules |
|---|:---:|---|
| Create | {create_supported} | {'Opens a dialog; server assigns the human-friendly reference and safe initial status.' if mutable else 'No direct creation; source workflows or report execution produce rows.'} |
| Read/list | Yes | Server-side paginated and ABAC-scoped. |
| Update | {update_supported} | {'Master records use optimistic versioning; operational records are editable only before posting/finalization.' if mutable else 'No direct update; change the authoritative source or report parameters.'} |
| Delete | {delete_supported} | {delete_rule} |
| Approve | {approve_supported} | {approval_rule} |
| Post/process | {process_supported} | {process_rule} |
| Reverse/void | {process_supported} | {'Dedicated POST action with mandatory reason and linked correction; never overwrite posted history.' if approvable else 'Not applicable; reverse or void the authoritative source record.'} |

## Create/edit dialog

{form_block}

## Detail dialog and nested tables

| Section | Content / nested columns | Behavior |
|---|---|---|
{detail_table}

All detail sections are collapsible `AppWorkspaceDetailPanel` instances. Mutations refresh the affected row, open detail, workspace counts, and shell badge without reloading unrelated tabs.

## Status model

| Status | Meaning | Allowed transition |
|---|---|---|
{status_table}

Raw backend enums must map to localized hospital language and `AppWorkspaceStatusBadge` tones.

## Permissions and entitlement

| Capability | Effective requirement |
|---|---|
| Route/tab/read | {permissions['read']} |
| Create/update/process | {permissions['write']} |
| Approve/reject/finalize | {permissions['approve']} |
| Export/print | {permissions['export']} |

{claims_permission_note}
Backend authorization is authoritative. Effective access is the union of grants intersected with subscription, assigned module, and ABAC scope. Denied menu entries and buttons are omitted rather than displayed as unusable chrome.

## Target API contract

| Operation | Method and target path | Notes |
|---|---|---|
{api_rows}

- JSON fields are `snake_case`; DTOs map explicitly to Dart domain entities.
- Success responses use `success`, `data`, and `meta`; errors use one safe problem-details shape with a stable code.
- Online-only financial actions are never queued offline.
- Workspace events are reconciliation hints; the client performs a targeted authoritative refresh.

## Validation

{validation}

Warnings are visibly distinct from blocking errors. Override actions require an allowed role, a reason, and an audit event.

## Audit and observability

- Log create, update, submit, approve/reject, post/process, allocation, reconciliation, reverse/void, archive/restore, export, and print events that apply.
- Capture actor, role, tenant/facility scope, timestamp, before/after summary, reason, source reference, version, IP/device context, and correlation ID.
- Never include secrets or unnecessary PHI in logs, errors, analytics, or export audit payloads.
- Record latency, result count, failures, and retry outcomes without exposing row data.

## Refactor work breakdown

1. **Navigation:** add `{tab.slug}` to the workspace section enum/query parser, canonical slug map, localized label, permission filter, and count-badge mapper.
2. **Presentation:** extract `frontend/lib/features/{tab.module_key}/presentation/widgets/{tab.slug.replace('-', '_')}_tab.dart`; compose it from `AppListTable` and shared workspace components.
3. **Table support:** define typed column IDs, default/optional columns, server sort keys, filters, export mapping, print mapping, empty/error states, and count semantics.
4. **Details and CRUD:** add focused detail and mutation dialogs; include the nested tables and buttons in this specification.
5. **State:** extend the workspace query/state/controller with a paginated result for this tab and targeted mutation refresh.
6. **Data layer:** add DTOs and explicit snake_case mappings, repository methods, optimistic version handling, and problem-details errors.
7. **Backend:** add schema, route, controller, service, and repository support under the target workspace; keep workflow transitions and postings transactional.
8. **Access:** add a tab/action atom matrix to the module access file using existing canonical permission keys.
9. **Tests:** cover route restoration, tab visibility, columns, filters, pagination, CRUD/action gates, statuses, export/print, detail nesting, refresh, and source-document links.
10. **Migration:** preserve existing compatible deep-link aliases, map legacy records/statuses explicitly, and remove old tab code only after parity tests pass.

## Implementation references

- Target page: `{tab.module['frontend']}`
- Target access matrix: `{tab.module['access']}`
- Target backend routes: `{tab.module['backend']}`
- Pharmacy page exemplar: `frontend/lib/features/pharmacy/presentation/pages/pharmacy_workspace_page.dart`
- Pharmacy tab mapping: `frontend/lib/features/pharmacy/presentation/widgets/pharmacy_scope_navigation.dart`
- Pharmacy access atoms: `frontend/lib/features/pharmacy/presentation/pharmacy_access.dart`
- Shared contracts: [{shared_link}/README.md]({shared_link}/README.md)

## Acceptance criteria

- [ ] Tab appears at `{title_path}` only with the required entitlement and read access.
- [ ] Canonical section slug `{tab.slug}` deep-links and restores the selected tab.
- [ ] Primary `AppListTable` exposes every tab-specific and applicable baseline column.
- [ ] Search, filters, server sort, pagination, column chooser, saved views, export, and print work.
- [ ] Buttons match this specification and are hidden when permission, status, or scope denies them.
- [ ] Create/edit and workflow operations use dialogs or contextual details, not permanent action tabs.
- [ ] Detail view contains related nested tables, attachments, and immutable audit history.
- [ ] Financial totals, count badges, and active filtered totals come from the server.
- [ ] Public UI/API/realtime references use human-friendly IDs and localized labels.
- [ ] Mutations refresh the affected row, detail, counts, and shell badge.
- [ ] Posted/finalized history cannot be edited or hard-deleted; corrections are linked and auditable.
- [ ] Empty, loading, partial, forbidden, conflict, and retryable error states follow shared workspace behavior.
"""


def render_folder_readme(
    folder: Path,
    title: str,
    tabs: list[Tab],
    child_folders: list[tuple[str, Path]],
) -> str:
    source_link = relative_link(folder / "README.md", SOURCE)
    shared_link = relative_link(
        folder / "README.md", OUTPUT_ROOT / "_shared" / "README.md"
    )
    tab_rows = []
    for tab in sorted(tabs, key=lambda item: item.label.lower()):
        tab_rows.append(
            f"| [{tab.label}]({tab.path.name}) | `{tab.slug}` | "
            f"{markdown_escape(purpose_for(tab).split('.')[0])}. |"
        )
    child_rows = []
    for child_title, child in sorted(child_folders, key=lambda item: item[0].lower()):
        child_rows.append(f"| [{child_title}]({child.name}/README.md) | Nested submenu and tab specifications. |")

    parts = [
        GENERATED_MARKER,
        f"# {title}",
        "",
        f"This folder is derived from [{SOURCE.name}]({source_link}) and represents a menu or nested submenu. Each non-README Markdown file represents one permanent table tab.",
        "",
    ]
    if child_rows:
        parts.extend(
            [
                "## Nested submenus",
                "",
                "| Submenu | Purpose |",
                "|---|---|",
                *child_rows,
                "",
            ]
        )
    if tab_rows:
        parts.extend(
            [
                "## Tabs",
                "",
                "| Tab | Section slug | Purpose |",
                "|---|---|---|",
                *tab_rows,
                "",
            ]
        )
    parts.extend(
        [
            "## Implementation contract",
            "",
            "- Every listed tab is an `AppListTable` worklist or tabular report.",
            "- Forms and workflow actions open from toolbar/row buttons in dialogs.",
            "- Permissions, entitlement, ABAC, human-friendly IDs, export/print, audit, and targeted refresh are mandatory.",
            f"- Use the [shared finance contracts]({shared_link}) for tables, dialogs, permissions, API behavior, state, and audit.",
            "",
        ]
    )
    return "\n".join(parts)


def shared_documents() -> dict[Path, str]:
    base = OUTPUT_ROOT / "_shared"
    docs: dict[Path, str] = {}
    docs[base / "README.md"] = f"""{GENERATED_MARKER}
# Shared finance workspace contracts

These contracts apply to all 159 permanent tabs under Billing, Accounts & Finance, and Insurance & Claims.

- [Workspace pattern](workspace-pattern.md)
- [Table contract](table-contract.md)
- [CRUD and dialog contract](crud-and-dialog-contract.md)
- [Permissions and entitlements](permissions-and-entitlements.md)
- [API, state, and audit contract](api-state-and-audit-contract.md)
- [Journal-entry shared columns](journal-entry-table-columns.md)
"""
    docs[base / "workspace-pattern.md"] = f"""{GENERATED_MARKER}
# Pharmacy-guided workspace pattern

Use Pharmacy as the interaction and component exemplar, not as a monolithic file-size exemplar.

## Required stack

1. `AsyncStateScaffold`
2. `ResponsivePage`
3. `AppWorkspace`
4. `AppTabStrip` for workspace tabs or Accounts nested-menu leaf selection
5. `AppListTable` for every permanent tab
6. `showAppDialog` + `AppDialog` / `AppWorkspaceMutationDialog` for details and mutations
7. `AppWorkspaceDetailPanel` for collapsible detail sections
8. `AppAccessActionGate` for each permission-aware action
9. Riverpod `AsyncNotifier` + repository + DTO mapper
10. `syncWorkspaceLocation` for canonical section slugs and deep links

## Pharmacy references

- `frontend/lib/features/pharmacy/presentation/pages/pharmacy_workspace_page.dart`
- `frontend/lib/features/pharmacy/presentation/widgets/pharmacy_scope_navigation.dart`
- `frontend/lib/features/pharmacy/presentation/widgets/pharmacy_catalog_panel.dart`
- `frontend/lib/features/pharmacy/presentation/pharmacy_access.dart`
- `frontend/lib/features/pharmacy/presentation/controllers/pharmacy_workspace_controller.dart`
- `backend/src/modules/pharmacy-workspace/`

## Refactor boundary

Extract section navigation, tables, detail dialogs, print helpers, and access atoms into focused files. Do not reproduce Pharmacy's large workspace page. Stock-alert-style tabs may share one table implementation with different server filter presets.
"""
    docs[base / "table-contract.md"] = f"""{GENERATED_MARKER}
# Finance table contract

Every permanent tab renders one primary `AppListTable`.

## Baseline columns

Add where applicable: Select, human-friendly Reference, Facility, Status, Created At, Created By, Updated At, Updated By, and Actions. Monetary tables also expose Currency.

## Required behavior

- Server search, filters, sorting, and pagination
- Sticky header and frozen identifying columns
- Column picker, reordering, density, and saved views
- Filtered server subtotals/grand totals
- Export and print using all matching permitted rows
- Responsive horizontal scrolling for wide tables
- Localized labels, dates, statuses, empty states, and errors
- No raw UUID/database IDs
- Active tab count from filtered total; inactive badge from summary
- Targeted row/count refresh after a mutation

Default columns are intentionally compact; every source-of-truth column remains selectable and exportable.
"""
    docs[base / "crud-and-dialog-contract.md"] = f"""{GENERATED_MARKER}
# Finance CRUD and dialog contract

## Placement

Create/edit/view are actions, not permanent tabs. Use `AppDialog` or `AppWorkspaceMutationDialog`; detail bodies use multiple `AppWorkspaceDetailPanel` sections.

## Lifecycle

- Master data: create, view, update, clone, activate/deactivate, soft archive/restore
- Draft operational data: create, view, update, submit, cancel
- Approved data: post/process only when period and source state permit
- Posted data: immutable; correct with reversal, void, credit/debit note, refund, or audited reopening
- Hard delete: never for referenced or posted financial records

## Detail composition

1. Summary/header
2. Context-specific nested line table
3. Related source documents
4. Attachments/evidence
5. Approval, posting, and immutable audit timeline

Mutations must refresh the affected row, open detail, tab counts, and shell badge.
"""
    docs[base / "permissions-and-entitlements.md"] = f"""{GENERATED_MARKER}
# Finance permissions and entitlements

| Menu | Read | Mutate | Approve | Entitlement |
|---|---|---|---|---|
| Billing | `billing:read` | `billing:write` | `billing:write` ∩ `financial:approve` | `billing-payments` |
| Accounts & Finance | `accounts:read` | `accounts:write` | `accounts:write` ∩ `financial:approve` | `facility-accounts` |
| Insurance & Claims | `claims:read` | `billing:write` (current canonical gate) | `billing:write` ∩ `financial:approve` | `insurance-claims` |

Export and print additionally require `evidence:export`.

Effective access is `union(role/module/user grants) ∩ subscription ∩ assigned modules ∩ ABAC`. Backend enforcement is authoritative. Unauthorized menus, tabs, columns, amounts, and buttons are omitted. Claims must not introduce `claims:write` until both canonical permission catalogs, seeds, roles, API gates, and frontend gates are updated together.
"""
    docs[base / "api-state-and-audit-contract.md"] = f"""{GENERATED_MARKER}
# Finance API, state, and audit contract

## API

- Business routes use `/api/v1/*`; routes are plural kebab-case and JSON is snake_case.
- Public payloads use `human_friendly_id`; raw primary keys never leave the backend.
- Lists return `success`, `data`, and pagination in `meta`.
- Mutations validate Zod schemas, ABAC scope, entitlement, permission, version, and workflow transition.
- Financial mutations use idempotency keys and database transactions.
- Operational cancel/void/reverse uses `POST /{{id}}/{{action}}` with a reason; DELETE is draft/master soft archive only.
- Online-only payment, posting, approval, reconciliation, and close actions are never queued offline.

## State

Use a module `AsyncNotifier`, repository, DTO mapper, paginated query, and targeted refresh. Realtime events are reconciliation hints. Defer event refresh while a mutation is saving.

## Audit

Log actor, role, tenant/facility, event, source reference, before/after summary, reason, version, IP/device context, timestamp, and correlation ID. Export/print events include filters and row count but no unnecessary PHI.
"""
    journal_columns = parse_source_columns()[("accounts", "All Journal Entries")]
    docs[base / "journal-entry-table-columns.md"] = f"""{GENERATED_MARKER}
# Shared journal-entry table columns

All Journal Entries and each typed journal tab use this schema with a fixed journal-type filter where applicable.

{table_columns_markdown(journal_columns)}

Every entry detail includes a balanced nested journal-line table. Debit must equal credit before approval or posting.
"""
    return docs


def root_readme(tabs: list[Tab]) -> str:
    counts = {
        key: sum(1 for tab in tabs if tab.module_key == key)
        for key in MODULES
    }
    return f"""{GENERATED_MARKER}
# Finance workspace tab specifications

This folder is the implementation-ready decomposition of [`../billing-accounts-finance.md`](../billing-accounts-finance.md), which remains the source of truth for product scope, menu hierarchy, tab labels, and table columns.

## Inventory

| Main menu | Route | Entitlement | Tabs | Documentation |
|---|---|---|---:|---|
| Billing | `/billing` | `billing-payments` | {counts['billing']} | [Open](billing/README.md) |
| Accounts & Finance | `/accounts` | `facility-accounts` | {counts['accounts']} | [Open](accounts-and-finance/README.md) |
| Insurance & Claims | `/claims` | `insurance-claims` | {counts['claims']} | [Open](insurance-and-claims/README.md) |
| **Total** |  |  | **{len(tabs)}** |  |

Folders represent menus and nested submenus. Every non-README tab file specifies purpose, columns, filters, buttons, CRUD, dialogs, nested tables, statuses, permissions, API behavior, validation, audit, implementation references, and acceptance criteria.

## Source-of-truth order

1. Security, privacy, compliance, API, module, permission, and subscription rules
2. `../billing-accounts-finance.md`
3. Shared contracts in [`_shared/`](_shared/README.md)
4. Individual tab files
5. Existing implementation where it does not conflict with the target specification

## Pharmacy implementation reference

The target workspaces use Pharmacy's proven route → query → tab strip → `AppListTable` → detail dialog → mutation dialog → targeted refresh pattern. They must not copy Pharmacy's monolithic page size or its known permission/pagination inconsistencies.

See [`_shared/workspace-pattern.md`](_shared/workspace-pattern.md).

## Important refactor rules

- Billing keeps the **Billing** menu name and exposes a flat tab workspace.
- Accounts becomes **Accounts & Finance** and is the only expandable finance main menu; category folders are submenu groups and leaf files are tabs.
- Insurance Claims becomes **Insurance & Claims** and exposes a flat tab workspace.
- Every permanent tab is a table/worklist. Create/edit/approve/post/reconcile actions are buttons and dialogs, not permanent tabs.
- Posted/finalized financial history is immutable.
- Cross-module links open the authoritative record in its owning workspace.

## Regeneration and verification

```powershell
python tool/generate_finance_tab_docs.py
python tool/generate_finance_tab_docs.py --check
```

The generator validates the 24 Billing, 100 Accounts & Finance, and 35 Insurance & Claims tabs against Section 10 columns before writing.
"""


def validate_output_links(outputs: dict[Path, str]) -> None:
    expected = {path.resolve() for path in outputs}
    broken: list[str] = []
    link_pattern = re.compile(r"\[[^\]]*\]\(([^)]+)\)")
    for path, content in outputs.items():
        for raw_target in link_pattern.findall(content):
            target = raw_target.split("#", 1)[0].strip()
            if not target or re.match(r"^[a-z]+://", target) or target.startswith("mailto:"):
                continue
            resolved = (path.parent / target).resolve()
            if resolved not in expected and not resolved.exists():
                broken.append(
                    f"{path.relative_to(REPO_ROOT)} -> {raw_target}"
                )
    if broken:
        raise ValueError("Broken generated Markdown links:\n- " + "\n- ".join(broken))


def validate_output_content(outputs: dict[Path, str], tabs: list[Tab]) -> None:
    required_headings = (
        "## Purpose",
        "## Navigation and workspace placement",
        "## Primary table columns",
        "## Filters",
        "### Toolbar buttons",
        "### Row buttons",
        "### Bulk buttons",
        "## CRUD and workflow contract",
        "## Detail dialog and nested tables",
        "## Permissions and entitlement",
        "## Target API contract",
        "## Refactor work breakdown",
        "## Acceptance criteria",
    )
    problems: list[str] = []
    if len({tab.path for tab in tabs}) != len(tabs):
        problems.append("duplicate tab output path detected")
    for path, content in outputs.items():
        for line_number, line in enumerate(content.splitlines(), start=1):
            if line != line.rstrip():
                problems.append(
                    f"{path.relative_to(REPO_ROOT)}:{line_number} trailing whitespace"
                )
    for tab in tabs:
        content = outputs.get(tab.path, "")
        for heading in required_headings:
            if heading not in content:
                problems.append(
                    f"{tab.path.relative_to(REPO_ROOT)} missing {heading}"
                )
    if problems:
        raise ValueError(
            "Generated documentation content validation failed:\n- "
            + "\n- ".join(problems)
        )


def build_outputs() -> dict[Path, str]:
    tabs = all_tabs()
    expected_counts = {"billing": 24, "accounts": 100, "claims": 35}
    actual_counts = {
        key: sum(1 for tab in tabs if tab.module_key == key)
        for key in expected_counts
    }
    if actual_counts != expected_counts:
        raise ValueError(
            f"Tab inventory mismatch: expected {expected_counts}, got {actual_counts}"
        )

    source_tabs = parse_source_tabs()
    for module_key in expected_counts:
        configured = {
            tab.label for tab in tabs if tab.module_key == module_key
        }
        authoritative = set(source_tabs[module_key])
        if configured != authoritative:
            missing_from_generator = sorted(authoritative - configured)
            missing_from_source = sorted(configured - authoritative)
            raise ValueError(
                f"Section 9 menu mismatch for {module_key}: "
                f"missing from generator={missing_from_generator}; "
                f"missing from source={missing_from_source}"
            )

    columns = parse_source_columns()
    missing = [
        f"{tab.module_key}: {tab.label}"
        for tab in tabs
        if (tab.module_key, tab.label) not in columns
    ]
    if missing:
        raise ValueError("Tabs missing source columns:\n- " + "\n- ".join(missing))

    outputs: dict[Path, str] = {
        OUTPUT_ROOT / "README.md": root_readme(tabs),
        **shared_documents(),
    }
    for tab in tabs:
        outputs[tab.path] = render_tab(tab, columns[(tab.module_key, tab.label)])

    folder_titles: dict[Path, str] = {}
    for module_key, module in MODULES.items():
        folder_titles[OUTPUT_ROOT / module["folder"]] = module["menu"]
    for tab in tabs:
        current = OUTPUT_ROOT / tab.module["folder"]
        for group_label, group_slug in zip(tab.group_labels, tab.group_slugs):
            current = current / group_slug
            folder_titles[current] = group_label

    for folder, title in folder_titles.items():
        direct_tabs = [tab for tab in tabs if tab.directory == folder]
        child_folders = [
            (child_title, child)
            for child, child_title in folder_titles.items()
            if child.parent == folder
        ]
        outputs[folder / "README.md"] = render_folder_readme(
            folder, title, direct_tabs, child_folders
        )

    normalized = {
        path: content.rstrip() + "\n" for path, content in outputs.items()
    }
    validate_output_content(normalized, tabs)
    validate_output_links(normalized)
    return normalized


def generate(check: bool) -> int:
    outputs = build_outputs()
    expected_paths = set(outputs)
    existing_paths = (
        set(OUTPUT_ROOT.rglob("*.md")) if OUTPUT_ROOT.exists() else set()
    )

    if check:
        problems: list[str] = []
        for path, expected in outputs.items():
            if not path.exists():
                problems.append(f"missing: {path.relative_to(REPO_ROOT)}")
                continue
            actual = path.read_text(encoding="utf-8")
            if actual != expected:
                problems.append(f"outdated: {path.relative_to(REPO_ROOT)}")
        for path in sorted(existing_paths - expected_paths):
            problems.append(f"unexpected: {path.relative_to(REPO_ROOT)}")
        if problems:
            print("Finance tab documentation check failed:")
            for problem in problems:
                print(f"- {problem}")
            return 1
        print(
            f"Finance tab documentation is current: "
            f"{len(all_tabs())} tab files, {len(outputs)} total Markdown files."
        )
        return 0

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    for stale in sorted(existing_paths - expected_paths):
        stale.unlink()

    print(
        f"Generated {len(all_tabs())} finance tab files and "
        f"{len(outputs) - len(all_tabs())} index/shared files under "
        f"{OUTPUT_ROOT.relative_to(REPO_ROOT)}."
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate finance tab specifications from the source-of-truth document."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files without writing.",
    )
    args = parser.parse_args()
    try:
        return generate(check=args.check)
    except (FileNotFoundError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
