const List<String> kLabCatalogCategories = <String>[
  'Blood Gas',
  'Cardiac',
  'Chemistry',
  'Coagulation',
  'Critical Care',
  'Endocrine',
  'Hematology',
  'Immunology',
  'Inflammation',
  'Lipids',
  'Liver',
  'Microbiology',
  'Nutrition',
  'Parasitology',
  'Renal',
  'Reproductive Health',
  'Serology',
  'Transfusion',
  'Tuberculosis',
  'Urinalysis',
  'Virology',
];

const List<String> kLabCatalogSpecimenTypes = <String>[
  'Arterial blood',
  'Blood culture',
  'Blood film',
  'Derived',
  'Nasopharyngeal swab',
  'Plasma',
  'Serum',
  'Serum / Plasma',
  'Serum / donor unit',
  'Serum / plasma / CSF',
  'Sputum / sample',
  'Stool',
  'Swab / body fluid',
  'Urine',
  'Whole blood',
  'Whole blood / Plasma',
  'Whole blood / Serum / Plasma',
];
