const REPORT_PANELS = Object.freeze([
  { id: 'overview', label_key: 'reports.workspace.panels.overview', default_resource: 'report-runs' },
  { id: 'catalog', label_key: 'reports.workspace.panels.catalog', default_resource: 'report-definitions' },
  { id: 'delivery', label_key: 'reports.workspace.panels.delivery', default_resource: 'report-runs' },
  { id: 'dashboards', label_key: 'reports.workspace.panels.dashboards', default_resource: 'dashboard-widgets' },
  { id: 'monitor', label_key: 'reports.workspace.panels.monitor', default_resource: 'kpi-snapshots' },
  { id: 'activity', label_key: 'reports.workspace.panels.activity', default_resource: 'analytics-events' },
]);

const REPORT_RESOURCE_BY_PANEL = Object.freeze(
  REPORT_PANELS.reduce((acc, panel) => {
    acc[panel.id] = panel.default_resource;
    return acc;
  }, {})
);

const REPORT_RESOURCES = Object.freeze([
  'report-definitions',
  'report-runs',
  'dashboard-widgets',
  'kpi-snapshots',
  'analytics-events',
]);

const REPORT_FORMATS = Object.freeze(['PDF', 'CSV', 'JSON', 'XLSX']);
const REPORT_DEFINITION_STATUSES = Object.freeze(['DRAFT', 'ACTIVE', 'ARCHIVED']);
const REPORT_RUN_STATUSES = Object.freeze(['QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED']);
const REPORT_TRIGGER_TYPES = Object.freeze(['MANUAL', 'SCHEDULED', 'RETRY']);
const REPORT_SCHEDULE_STATUSES = Object.freeze(['ACTIVE', 'PAUSED']);
const REPORT_SCHEDULE_FREQUENCIES = Object.freeze(['DAILY', 'WEEKLY', 'MONTHLY']);
const REPORT_WIDGET_TYPES = Object.freeze(['TABLE', 'KPI', 'LINE_CHART', 'BAR_CHART', 'AREA_CHART', 'DONUT_CHART']);
const KPI_THRESHOLD_STATES = Object.freeze(['NORMAL', 'WARNING', 'CRITICAL']);
const ANALYTICS_EVENT_SEVERITIES = Object.freeze(['INFO', 'WARNING', 'ERROR', 'CRITICAL']);

const REPORT_DEFAULT_RETENTION_DAYS = 30;
const REPORT_RUNNER_POLL_INTERVAL_MS = 60_000;
const REPORT_RUNNER_MAX_CONCURRENCY = 2;
const REPORT_SCHEDULE_LEASE_MS = 5 * 60_000;

const REPORT_DATASETS = Object.freeze([
  {
    key: 'patient_registrations',
    label: 'Patient registrations',
    category: 'patients',
    description: 'Registration volume and facility mix over time.',
    visualization: 'LINE_CHART',
    default_columns: ['date', 'registrations', 'facility'],
  },
  {
    key: 'appointment_throughput_no_shows',
    label: 'Appointment throughput and no-shows',
    category: 'appointments',
    description: 'Operational throughput and missed appointments.',
    visualization: 'BAR_CHART',
    default_columns: ['date', 'scheduled', 'completed', 'no_show'],
  },
  {
    key: 'billing_collections_open_balances',
    label: 'Billing collections, expenditures, and profit',
    category: 'billing',
    description:
      'Period collections, expenditures (refunds and write-offs), profit proxy, and invoice workload.',
    visualization: 'AREA_CHART',
    default_columns: [
      'date',
      'collections',
      'expenditures',
      'profit_proxy',
      'refunds',
      'write_offs',
      'net_collections',
      'issued_invoices',
      'open_invoices',
    ],
  },
  {
    key: 'insurance_claims_aging',
    label: 'Insurance claims aging',
    category: 'billing',
    description: 'Claim status distribution and aging buckets.',
    visualization: 'DONUT_CHART',
    default_columns: ['bucket', 'claims', 'status'],
  },
  {
    key: 'pharmacy_drug_consumption',
    label: 'Pharmacy drug consumption',
    category: 'pharmacy',
    description:
      'Top dispensed drugs by quantity and amount for a period, with walk-in (PHARMACY) vs clinical order-source mix and profit when buy cost is configured.',
    visualization: 'BAR_CHART',
    default_columns: ['drug', 'quantity_dispensed', 'amount', 'profit', 'order_source'],
  },
  {
    key: 'pharmacy_dispense_throughput',
    label: 'Pharmacy dispense throughput',
    category: 'pharmacy',
    description:
      'Order creation and dispense status throughput over time, including returns when logged.',
    visualization: 'LINE_CHART',
    default_columns: [
      'date',
      'orders_created',
      'dispensed',
      'partially_dispensed',
      'cancelled',
      'returns',
    ],
  },
  {
    key: 'pharmacy_sales_by_category',
    label: 'Pharmacy sales by category',
    category: 'pharmacy',
    description:
      'Dispense revenue grouped by inventory_item.category via drug_inventory_map.',
    visualization: 'BAR_CHART',
    default_columns: ['category', 'quantity_dispensed', 'amount'],
  },
  {
    key: 'pharmacy_sales_by_branch',
    label: 'Pharmacy sales by branch',
    category: 'pharmacy',
    description: 'Dispense revenue grouped by patient facility (branch).',
    visualization: 'BAR_CHART',
    default_columns: ['facility', 'amount', 'quantity_dispensed'],
  },
  {
    key: 'pharmacy_profit_by_branch',
    label: 'Pharmacy profit by branch',
    category: 'pharmacy',
    description:
      'Dispense retail profit (unit_price − buy_unit_price) × qty grouped by patient facility.',
    visualization: 'BAR_CHART',
    default_columns: ['facility', 'profit', 'amount'],
  },
  {
    key: 'pharmacy_stock_by_branch',
    label: 'Pharmacy stock by branch',
    category: 'pharmacy',
    description: 'On-hand inventory quantity and value grouped by facility.',
    visualization: 'BAR_CHART',
    default_columns: ['facility', 'quantity', 'value'],
  },
  {
    key: 'pharmacy_purchases_by_branch',
    label: 'Pharmacy purchases by branch',
    category: 'pharmacy',
    description:
      'Purchase request and linked purchase order counts by facility (PO line amounts not modeled).',
    visualization: 'TABLE',
    default_columns: ['facility', 'request_count', 'order_count'],
  },
  {
    key: 'pharmacy_stock_shortages_by_branch',
    label: 'Pharmacy stock shortages by branch',
    category: 'pharmacy',
    description:
      'LOW / CRITICAL / OUT_OF_STOCK inventory risk counts grouped by facility.',
    visualization: 'TABLE',
    default_columns: [
      'facility',
      'shortage_count',
      'low_count',
      'critical_count',
      'out_of_stock_count',
      'quantity',
    ],
  },
  {
    key: 'pharmacy_best_performing_branch',
    label: 'Best-performing branch',
    category: 'pharmacy',
    description: 'Facilities ranked by dispense amount or profit.',
    visualization: 'TABLE',
    default_columns: ['rank', 'facility', 'amount', 'profit', 'quantity_dispensed'],
  },
  {
    key: 'pharmacy_branch_comparison',
    label: 'Branch comparison',
    category: 'pharmacy',
    description:
      'Side-by-side facility comparison of sales, profit, stock, shortages, and purchases.',
    visualization: 'BAR_CHART',
    default_columns: [
      'facility',
      'amount',
      'profit',
      'quantity_dispensed',
      'quantity',
      'value',
      'shortage_count',
      'request_count',
      'order_count',
    ],
  },
  {
    key: 'pharmacy_transfers_between_branches',
    label: 'Transfers between branches',
    category: 'pharmacy',
    description:
      'TRANSFER stock_movement groups aggregated by from_facility → to_facility.',
    visualization: 'TABLE',
    default_columns: ['sending_branch', 'receiving_branch', 'quantity', 'transfer_count'],
  },
  {
    key: 'pharmacy_transfer_quantity',
    label: 'Transfer quantity',
    category: 'pharmacy',
    description: 'TRANSFER stock_movement rows with unit quantities and endpoints.',
    visualization: 'TABLE',
    default_columns: [
      'occurred_at',
      'inventory_item',
      'quantity',
      'sending_branch',
      'receiving_branch',
      'transfer_leg',
    ],
  },
  {
    key: 'pharmacy_sending_branch',
    label: 'Sending branch',
    category: 'pharmacy',
    description: 'TRANSFER ship legs grouped by from_facility.',
    visualization: 'BAR_CHART',
    default_columns: ['facility', 'quantity', 'transfer_count'],
  },
  {
    key: 'pharmacy_receiving_branch',
    label: 'Receiving branch',
    category: 'pharmacy',
    description: 'TRANSFER destinations grouped by to_facility.',
    visualization: 'BAR_CHART',
    default_columns: ['facility', 'quantity', 'transfer_count'],
  },
  {
    key: 'pharmacy_transfer_date',
    label: 'Transfer date',
    category: 'pharmacy',
    description: 'Transfer groups rolled up by occurred_at day.',
    visualization: 'LINE_CHART',
    default_columns: ['transfer_date', 'quantity', 'transfer_count'],
  },
  {
    key: 'pharmacy_transfer_status',
    label: 'Transfer status',
    category: 'pharmacy',
    description:
      'PENDING|COMPLETED derived from paired ship/receive legs (transfer_group_id).',
    visualization: 'TABLE',
    default_columns: [
      'transfer_date',
      'transfer_status',
      'inventory_item',
      'sending_branch',
      'receiving_branch',
      'quantity',
    ],
  },
  {
    key: 'pharmacy_products_transferred',
    label: 'Products transferred',
    category: 'pharmacy',
    description: 'Transfer groups with product, quantity, facilities, and date.',
    visualization: 'TABLE',
    default_columns: [
      'inventory_item',
      'quantity',
      'sending_branch',
      'receiving_branch',
      'transfer_date',
      'transfer_status',
    ],
  },
  {
    key: 'pharmacy_pending_transfers',
    label: 'Pending transfers',
    category: 'pharmacy',
    description: 'TRANSFER groups with a ship leg and no matching receive leg.',
    visualization: 'TABLE',
    default_columns: [
      'transfer_date',
      'inventory_item',
      'quantity',
      'sending_branch',
      'receiving_branch',
      'transfer_status',
    ],
  },
  {
    key: 'pharmacy_transfer_discrepancies',
    label: 'Transfer discrepancies',
    category: 'pharmacy',
    description: 'Paired transfers where abs(shipped − received) > 0.',
    visualization: 'TABLE',
    default_columns: [
      'transfer_date',
      'inventory_item',
      'sending_branch',
      'receiving_branch',
      'shipped_quantity',
      'received_quantity',
      'discrepancy_quantity',
    ],
  },
  {
    key: 'pharmacy_sales_by_customer',
    label: 'Pharmacy sales by customer',
    category: 'pharmacy',
    description: 'Dispense revenue grouped by pharmacy order patient.',
    visualization: 'BAR_CHART',
    default_columns: ['patient', 'amount', 'quantity_dispensed'],
  },
  {
    key: 'pharmacy_sales_payment_methods',
    label: 'Pharmacy sales by payment method',
    category: 'pharmacy',
    description: 'Pharmacy-scoped payment totals by PaymentMethodType.',
    visualization: 'DONUT_CHART',
    default_columns: ['method', 'amount'],
  },
  {
    key: 'pharmacy_sales_discounts',
    label: 'Pharmacy discounts',
    category: 'pharmacy',
    description: 'Negative applied billing adjustments on pharmacy invoices.',
    visualization: 'TABLE',
    default_columns: ['date', 'amount', 'reason'],
  },
  {
    key: 'pharmacy_sales_refunds',
    label: 'Pharmacy refunds and returns',
    category: 'pharmacy',
    description: 'Pharmacy refund amounts and dispense return counts by period.',
    visualization: 'TABLE',
    default_columns: ['date', 'amount', 'returns'],
  },
  {
    key: 'pharmacy_sales_net_revenue',
    label: 'Pharmacy net revenue',
    category: 'pharmacy',
    description: 'Gross dispense revenue minus pharmacy refunds and discounts.',
    visualization: 'KPI',
    default_columns: ['metric', 'amount'],
  },
  {
    key: 'pharmacy_sales_avg_transaction',
    label: 'Pharmacy average transaction value',
    category: 'pharmacy',
    description: 'Period gross dispense amount divided by orders_created.',
    visualization: 'KPI',
    default_columns: ['average_transaction_value', 'orders_created', 'amount'],
  },
  {
    key: 'pharmacy_financial_revenue',
    label: 'Pharmacy revenue',
    category: 'pharmacy',
    description: 'Dispense retail amount by period (consumption ledger).',
    visualization: 'LINE_CHART',
    default_columns: ['date', 'amount'],
  },
  {
    key: 'pharmacy_financial_cogs',
    label: 'Pharmacy cost of goods sold',
    category: 'pharmacy',
    description: 'Σ buy_unit_price × quantity_dispensed for DISPENSED logs (unset buy → 0).',
    visualization: 'TABLE',
    default_columns: ['date', 'cogs'],
  },
  {
    key: 'pharmacy_financial_gross_profit',
    label: 'Pharmacy gross profit',
    category: 'pharmacy',
    description:
      'Dispense retail margin by period (null buy → 0 in rollup; not billing profit_proxy).',
    visualization: 'TABLE',
    default_columns: ['date', 'profit', 'amount'],
  },
  {
    key: 'pharmacy_financial_net_profit',
    label: 'Pharmacy net profit',
    category: 'pharmacy',
    description: 'Gross dispense profit minus pharmacy refunds and write-offs.',
    visualization: 'KPI',
    default_columns: ['metric', 'amount'],
  },
  {
    key: 'pharmacy_financial_operating_expenses',
    label: 'Pharmacy operating expenses',
    category: 'pharmacy',
    description:
      'Pharmacy-scoped billing expenditures (refunds + write-offs from billing runner).',
    visualization: 'TABLE',
    default_columns: ['date', 'expenditures'],
  },
  {
    key: 'pharmacy_financial_receivables',
    label: 'Pharmacy customer receivables',
    category: 'pharmacy',
    description: 'Open pharmacy invoice balance_due totals.',
    visualization: 'TABLE',
    default_columns: ['patient', 'amount', 'issued_at'],
  },
  {
    key: 'pharmacy_financial_cash_flow',
    label: 'Pharmacy cash flow',
    category: 'pharmacy',
    description: 'Pharmacy-scoped billing collections, refunds, and net_collections.',
    visualization: 'AREA_CHART',
    default_columns: ['date', 'collections', 'refunds', 'net_collections'],
  },
  {
    key: 'pharmacy_financial_profit_by_category',
    label: 'Pharmacy profit by product/category',
    category: 'pharmacy',
    description: 'Dispense retail margin grouped by inventory_item.category.',
    visualization: 'BAR_CHART',
    default_columns: ['category', 'profit', 'amount'],
  },
  {
    key: 'pharmacy_financial_profit_by_period',
    label: 'Pharmacy profit by period',
    category: 'pharmacy',
    description: 'Dispense retail margin daily/monthly series.',
    visualization: 'LINE_CHART',
    default_columns: ['date', 'profit', 'amount'],
  },
  {
    key: 'pharmacy_sales_by_staff',
    label: 'Pharmacy sales by staff',
    category: 'pharmacy',
    description:
      'Dispense revenue attributed via pharmacy_dispense_attestation.attested_by_user_id.',
    visualization: 'BAR_CHART',
    default_columns: ['staff', 'amount', 'quantity_dispensed'],
  },
  {
    key: 'pharmacy_dispensing_by_staff',
    label: 'Pharmacy dispensing by staff',
    category: 'pharmacy',
    description: 'Order and pack counts by attestation actor.',
    visualization: 'BAR_CHART',
    default_columns: ['staff', 'orders_created', 'quantity_dispensed'],
  },
  {
    key: 'pharmacy_purchases_by_staff',
    label: 'Purchases entered by staff',
    category: 'pharmacy',
    description: 'Audit CREATE counts on purchase_order and goods_receipt.',
    visualization: 'TABLE',
    default_columns: ['staff', 'event_count'],
  },
  {
    key: 'pharmacy_stock_adjustments_by_staff',
    label: 'Stock adjustments by staff',
    category: 'pharmacy',
    description:
      'Audit CREATE/UPDATE on stock_adjustment (model has no adjusted_by_user_id).',
    visualization: 'TABLE',
    default_columns: ['staff', 'event_count'],
  },
  {
    key: 'pharmacy_refunds_by_staff',
    label: 'Refunds by staff',
    category: 'pharmacy',
    description: 'Pharmacy refund amounts attributed via audit CREATE user_id.',
    visualization: 'TABLE',
    default_columns: ['staff', 'amount', 'event_count'],
  },
  {
    key: 'pharmacy_discounts_authorized',
    label: 'Discounts authorized by staff',
    category: 'pharmacy',
    description: 'Negative pharmacy billing_adjustment amounts via audit actor.',
    visualization: 'TABLE',
    default_columns: ['staff', 'amount', 'event_count'],
  },
  {
    key: 'pharmacy_voided_transactions',
    label: 'Voided transactions by staff',
    category: 'pharmacy',
    description: 'CANCELLED pharmacy_order counts plus audit DELETE voids by staff.',
    visualization: 'TABLE',
    default_columns: ['staff', 'voided_count'],
  },
  {
    key: 'pharmacy_login_activity',
    label: 'Login and activity history',
    category: 'pharmacy',
    description: 'audit_log LOGIN/LOGOUT events with user and timestamp.',
    visualization: 'TABLE',
    default_columns: ['timestamp', 'staff', 'action'],
  },
  {
    key: 'pharmacy_user_productivity',
    label: 'User productivity',
    category: 'pharmacy',
    description: 'Attestation-linked dispenses and amounts per staff per day.',
    visualization: 'LINE_CHART',
    default_columns: ['date', 'staff', 'quantity_dispensed', 'amount'],
  },
  {
    key: 'pharmacy_audit_trail',
    label: 'Pharmacy audit trail',
    category: 'pharmacy',
    description: 'Pharmacy-relevant audit_log rows (diff gated by compliance permission).',
    visualization: 'TABLE',
    default_columns: ['timestamp', 'action', 'entity', 'entity_id', 'staff', 'diff'],
  },
  {
    key: 'pharmacy_controlled_stock',
    label: 'Controlled medicine stock',
    category: 'pharmacy',
    description: 'On-hand quantity for drug.is_controlled (grain=drug).',
    visualization: 'TABLE',
    default_columns: ['drug', 'facility', 'quantity', 'batch_number', 'unit'],
  },
  {
    key: 'pharmacy_controlled_balance',
    label: 'Controlled medicine balance',
    category: 'pharmacy',
    description:
      'Opening/closing balance for controlled drugs. Grain=drug. closing=opening+received−dispensed−wastage+adjustments_net.',
    visualization: 'TABLE',
    default_columns: [
      'drug',
      'facility',
      'opening_quantity',
      'quantity_received',
      'quantity_dispensed',
      'wastage',
      'adjustments_net',
      'closing_quantity',
      'unit',
    ],
  },
  {
    key: 'pharmacy_controlled_received',
    label: 'Controlled quantity received',
    category: 'pharmacy',
    description: 'INBOUND+PURCHASE stock_movement for controlled drugs.',
    visualization: 'TABLE',
    default_columns: ['occurred_at', 'drug', 'quantity', 'facility', 'unit'],
  },
  {
    key: 'pharmacy_controlled_dispensed',
    label: 'Controlled quantity dispensed',
    category: 'pharmacy',
    description: 'dispense_log status=DISPENSED for controlled drugs.',
    visualization: 'TABLE',
    default_columns: [
      'dispensed_at',
      'drug',
      'quantity_dispensed',
      'batch_number',
      'patient',
      'unit',
    ],
  },
  {
    key: 'pharmacy_controlled_batches',
    label: 'Controlled batch numbers',
    category: 'pharmacy',
    description: 'drug_batch rows for drug.is_controlled.',
    visualization: 'TABLE',
    default_columns: ['drug', 'batch_number', 'quantity', 'expiry_date', 'unit'],
  },
  {
    key: 'pharmacy_controlled_actors',
    label: 'Controlled dispense actors',
    category: 'pharmacy',
    description:
      'Prescriber (encounter.provider), patient, and dispensing staff (attestation) for controlled dispenses.',
    visualization: 'TABLE',
    default_columns: [
      'actor_role',
      'actor',
      'drug',
      'quantity_dispensed',
      'dispensed_at',
    ],
  },
  {
    key: 'pharmacy_controlled_adjustments',
    label: 'Controlled adjustments',
    category: 'pharmacy',
    description: 'ADJUSTMENT movements/adjustments excluding EXPIRY|DAMAGE for controlled drugs.',
    visualization: 'TABLE',
    default_columns: ['adjusted_at', 'drug', 'quantity', 'reason', 'facility', 'unit'],
  },
  {
    key: 'pharmacy_controlled_wastage',
    label: 'Controlled wastage',
    category: 'pharmacy',
    description: 'EXPIRY|DAMAGE qty for controlled drugs.',
    visualization: 'TABLE',
    default_columns: ['adjusted_at', 'drug', 'quantity', 'reason', 'facility', 'unit'],
  },
  {
    key: 'pharmacy_controlled_regulatory_log',
    label: 'Controlled regulatory log',
    category: 'pharmacy',
    description:
      'Chronological receive/dispense/adjust/waste for controlled drugs. Requires compliance:read.',
    visualization: 'TABLE',
    default_columns: [
      'occurred_at',
      'event_type',
      'drug',
      'quantity',
      'batch_number',
      'actor',
    ],
  },
  {
    key: 'pharmacy_audit_who_created',
    label: 'Who created a transaction',
    category: 'pharmacy',
    description: 'Pharmacy-relevant audit_log CREATE rows.',
    visualization: 'TABLE',
    default_columns: ['user', 'entity', 'entity_id', 'created_at'],
  },
  {
    key: 'pharmacy_audit_who_edited',
    label: 'Who edited it',
    category: 'pharmacy',
    description: 'Pharmacy-relevant audit_log UPDATE rows.',
    visualization: 'TABLE',
    default_columns: ['user', 'entity', 'entity_id', 'created_at'],
  },
  {
    key: 'pharmacy_audit_who_deleted',
    label: 'Who deleted/voided it',
    category: 'pharmacy',
    description: 'Pharmacy-relevant audit_log DELETE and CANCELLED domain events.',
    visualization: 'TABLE',
    default_columns: ['user', 'entity', 'entity_id', 'created_at', 'action'],
  },
  {
    key: 'pharmacy_audit_previous_vs_new',
    label: 'Previous vs new values',
    category: 'pharmacy',
    description: 'Field-level audit_log diff_json projections (prices as currency, qty as units).',
    visualization: 'TABLE',
    default_columns: [
      'changed_at',
      'user',
      'entity',
      'entity_id',
      'field',
      'previous_amount',
      'new_amount',
      'previous_quantity',
      'new_quantity',
      'previous_value',
      'new_value',
      'currency',
    ],
  },
  {
    key: 'pharmacy_audit_change_datetime',
    label: 'Date/time of changes',
    category: 'pharmacy',
    description: 'Pharmacy-relevant audit_log rows ordered by created_at.',
    visualization: 'TABLE',
    default_columns: ['created_at', 'user', 'action', 'entity', 'entity_id'],
  },
  {
    key: 'pharmacy_audit_stock_adjustments',
    label: 'Audit stock adjustments',
    category: 'pharmacy',
    description: 'audit_log rows for stock_adjustment and stock_movement entities.',
    visualization: 'TABLE',
    default_columns: ['created_at', 'user', 'action', 'entity', 'entity_id', 'diff'],
  },
  {
    key: 'pharmacy_audit_price_changes',
    label: 'Audit price changes',
    category: 'pharmacy',
    description: 'audit_log UPDATE on drug with price keys in diff_json.',
    visualization: 'TABLE',
    default_columns: [
      'changed_at',
      'user',
      'entity_id',
      'field',
      'previous_amount',
      'new_amount',
      'currency',
    ],
  },
  {
    key: 'pharmacy_audit_user_permissions',
    label: 'User permissions audit',
    category: 'pharmacy',
    description: 'Permission-assignment audit_log rows when present.',
    visualization: 'TABLE',
    default_columns: [
      'created_at',
      'user',
      'action',
      'entity',
      'entity_id',
      'field',
      'previous_value',
      'new_value',
    ],
  },
  {
    key: 'pharmacy_audit_unauthorized',
    label: 'Unauthorized attempts',
    category: 'pharmacy',
    description: 'Denied ACCESS/EXPORT pharmacy audit_log rows when logged.',
    visualization: 'TABLE',
    default_columns: ['created_at', 'user', 'action', 'entity', 'entity_id', 'reason'],
  },
  {
    key: 'pharmacy_audit_rx_controlled',
    label: 'Prescription/controlled-drug audit trail',
    category: 'pharmacy',
    description: 'audit_log for pharmacy_order, dispense_log, and attestation entities.',
    visualization: 'TABLE',
    default_columns: ['created_at', 'user', 'action', 'entity', 'entity_id', 'diff'],
  },
  {
    key: 'pharmacy_dispensing_by_prescriber',
    label: 'Medicines dispensed by prescriber',
    category: 'pharmacy',
    description:
      'DISPENSED pack qty grouped by encounter.provider (clinical orders with linked clinician only).',
    visualization: 'BAR_CHART',
    default_columns: ['prescriber', 'quantity_dispensed'],
  },
  {
    key: 'pharmacy_dispensing_partial',
    label: 'Partial dispensing',
    category: 'pharmacy',
    description:
      'PARTIALLY_DISPENSED order counts and remaining pack qty (ordered − DISPENSED logs).',
    visualization: 'TABLE',
    default_columns: ['status', 'orders_created', 'remaining_quantity'],
  },
  {
    key: 'pharmacy_dispensing_frequency',
    label: 'Prescription frequency',
    category: 'pharmacy',
    description: 'Pharmacy order counts grouped by patient for the period.',
    visualization: 'BAR_CHART',
    default_columns: ['patient', 'orders_created'],
  },
  {
    key: 'pharmacy_dispensing_avg_items',
    label: 'Average items per prescription',
    category: 'pharmacy',
    description: 'pharmacy_order_item count divided by pharmacy_order count in range.',
    visualization: 'KPI',
    default_columns: ['average_items_per_prescription', 'item_count', 'orders_created'],
  },
  {
    key: 'pharmacy_prescription_count',
    label: 'Prescription count',
    category: 'pharmacy',
    description: 'pharmacy_order count in range (aligns with throughput orders_created).',
    visualization: 'KPI',
    default_columns: ['orders_created'],
  },
  {
    key: 'pharmacy_prescription_prescriber',
    label: 'Prescriber',
    category: 'pharmacy',
    description:
      'Pharmacy order counts grouped by encounter.provider (clinical orders with linked clinician only).',
    visualization: 'BAR_CHART',
    default_columns: ['prescriber', 'orders_created'],
  },
  {
    key: 'pharmacy_prescription_diagnosis',
    label: 'Diagnosis/indication',
    category: 'pharmacy',
    description:
      'Pharmacy order counts grouped by encounter diagnosis when encounter_id is set.',
    visualization: 'BAR_CHART',
    default_columns: ['diagnosis', 'orders_created'],
  },
  {
    key: 'pharmacy_prescription_medicine',
    label: 'Medicine prescribed',
    category: 'pharmacy',
    description: 'pharmacy_order_item counts and quantity grouped by drug.name.',
    visualization: 'BAR_CHART',
    default_columns: ['drug', 'item_count', 'quantity'],
  },
  {
    key: 'pharmacy_prescription_dosage',
    label: 'Dosage',
    category: 'pharmacy',
    description:
      'Order-item dosage plain labels (dosage or dose_amount+dose_unit) with item counts.',
    visualization: 'BAR_CHART',
    default_columns: ['dosage', 'item_count'],
  },
  {
    key: 'pharmacy_prescription_frequency',
    label: 'Frequency',
    category: 'pharmacy',
    description: 'pharmacy_order_item.frequency plain values with item counts.',
    visualization: 'BAR_CHART',
    default_columns: ['frequency', 'item_count'],
  },
  {
    key: 'pharmacy_prescription_duration',
    label: 'Duration',
    category: 'pharmacy',
    description:
      'duration_value + duration_unit plain; duration_days when unit converts to days.',
    visualization: 'TABLE',
    default_columns: ['duration', 'duration_days', 'item_count'],
  },
  {
    key: 'pharmacy_prescription_antibiotic_usage',
    label: 'Antibiotic usage',
    category: 'pharmacy',
    description:
      'DISPENSED pack qty for drugs whose code is in the documented ANTI_INFECTIVE seed set.',
    visualization: 'BAR_CHART',
    default_columns: ['drug', 'quantity_dispensed'],
  },
  {
    key: 'pharmacy_prescription_controlled_dispensing',
    label: 'Controlled-drug dispensing',
    category: 'pharmacy',
    description:
      'DISPENSED pack qty for Morphine/Tramadol allow-list codes (MRF10I, TRM50) — no is_controlled column.',
    visualization: 'BAR_CHART',
    default_columns: ['drug', 'quantity_dispensed'],
  },
  {
    key: 'pharmacy_customer_count',
    label: 'Pharmacy number of customers',
    category: 'pharmacy',
    description: 'Distinct pharmacy_order.patient_id count in period.',
    visualization: 'KPI',
    default_columns: ['customer_count'],
  },
  {
    key: 'pharmacy_customers_new_vs_returning',
    label: 'Pharmacy new vs returning customers',
    category: 'pharmacy',
    description:
      'New = first-ever pharmacy order in range with none before from; returning = prior order before from and again in range.',
    visualization: 'DONUT_CHART',
    default_columns: ['segment', 'customer_count'],
  },
  {
    key: 'pharmacy_patient_medication_history',
    label: 'Pharmacy patient medication history',
    category: 'pharmacy',
    description:
      'Dispense lines in period with patient label, drug, quantity, dispensed_at, and amount.',
    visualization: 'TABLE',
    default_columns: [
      'patient',
      'drug',
      'quantity_dispensed',
      'dispensed_at',
      'amount',
    ],
  },
  {
    key: 'pharmacy_customer_credit_balance',
    label: 'Pharmacy customer credit balance',
    category: 'pharmacy',
    description:
      'Sum of open pharmacy invoice balances per patient (status DRAFT|SENT|OVERDUE, balance_due > 0).',
    visualization: 'TABLE',
    default_columns: ['patient', 'credit_balance'],
  },
  {
    key: 'pharmacy_customer_outstanding',
    label: 'Pharmacy outstanding payments',
    category: 'pharmacy',
    description:
      'Open pharmacy invoices with balance due (same open status set as billing module).',
    visualization: 'TABLE',
    default_columns: ['patient', 'amount', 'issued_at'],
  },
  {
    key: 'pharmacy_customer_demographics',
    label: 'Pharmacy customer demographics',
    category: 'pharmacy',
    description:
      'Aggregate gender and age-band counts for patients with pharmacy orders in period (no individual PHI columns).',
    visualization: 'BAR_CHART',
    default_columns: ['dimension', 'bucket', 'customer_count'],
  },
  {
    key: 'pharmacy_customer_retention',
    label: 'Pharmacy customer retention',
    category: 'pharmacy',
    description:
      'Share of prior-window purchasers who also purchase in the current window (equal-length prior window).',
    visualization: 'KPI',
    default_columns: ['segment', 'customer_count', 'retention_rate'],
  },
  {
    key: 'inventory_stock_risk',
    label: 'Inventory stock risk',
    category: 'inventory',
    description:
      'On-hand stock plus low-stock, overstock, critical, near-expiry, and expired drug batch pressure. Expiry value at buy cost; windows 0-30/30-60/60-90/90-180.',
    visualization: 'KPI',
    default_columns: [
      'facility',
      'inventory_item',
      'quantity',
      'reorder_level',
      'risk_state',
      'expiry_date',
      'expiry_alert_status',
      'days_to_expiry',
      'expiry_window',
      'batch_number',
      'value',
      'category',
      'supplier',
      'supplier_id',
      'drug',
    ],
  },
  {
    key: 'inventory_stock_value',
    label: 'Inventory stock value',
    category: 'inventory',
    description:
      'On-hand quantity × unit cost (prefer buy_unit_price via drug_inventory_map).',
    visualization: 'TABLE',
    default_columns: [
      'facility',
      'inventory_item',
      'quantity',
      'unit_cost',
      'value',
      'cost_basis',
      'risk_state',
    ],
  },
  {
    key: 'inventory_opening_closing',
    label: 'Opening and closing stock',
    category: 'inventory',
    description:
      'Closing = current on-hand; opening reconstructed from period stock_movement and stock_adjustment net.',
    visualization: 'TABLE',
    default_columns: [
      'inventory_item',
      'facility',
      'opening_quantity',
      'closing_quantity',
      'unit',
    ],
  },
  {
    key: 'inventory_stock_received',
    label: 'Stock received',
    category: 'inventory',
    description: 'INBOUND stock_movement rows with reason PURCHASE.',
    visualization: 'TABLE',
    default_columns: ['occurred_at', 'inventory_item', 'quantity', 'facility'],
  },
  {
    key: 'inventory_stock_issued',
    label: 'Stock issued',
    category: 'inventory',
    description: 'OUTBOUND stock_movement rows with reason DISPENSE.',
    visualization: 'TABLE',
    default_columns: ['occurred_at', 'inventory_item', 'quantity', 'facility'],
  },
  {
    key: 'inventory_stock_adjustments',
    label: 'Stock adjustments',
    category: 'inventory',
    description: 'stock_adjustment rows for the selected period.',
    visualization: 'TABLE',
    default_columns: [
      'adjusted_at',
      'inventory_item',
      'quantity',
      'reason',
      'facility',
    ],
  },
  {
    key: 'inventory_damaged_stock',
    label: 'Damaged stock',
    category: 'inventory',
    description: 'stock_adjustment rows with reason DAMAGE.',
    visualization: 'TABLE',
    default_columns: [
      'adjusted_at',
      'inventory_item',
      'quantity',
      'value',
      'facility',
    ],
  },
  {
    key: 'inventory_lost_stock',
    label: 'Lost or missing stock',
    category: 'inventory',
    description:
      'stock_adjustment reason=OTHER as loss proxy (DAMAGE excluded; no LOSS enum).',
    visualization: 'TABLE',
    default_columns: [
      'adjusted_at',
      'inventory_item',
      'quantity',
      'reason',
      'value',
      'facility',
    ],
  },
  {
    key: 'inventory_stock_write_offs',
    label: 'Stock write-offs',
    category: 'inventory',
    description:
      'stock_adjustment EXPIRY|DAMAGE write-offs with quantity and value at buy cost.',
    visualization: 'TABLE',
    default_columns: [
      'adjusted_at',
      'inventory_item',
      'reason',
      'quantity',
      'value',
      'amount',
      'facility',
    ],
  },
  {
    key: 'inventory_adjustment_reasons',
    label: 'Adjustment reasons',
    category: 'inventory',
    description: 'stock_adjustment grouped by reason with counts, quantity, and value.',
    visualization: 'TABLE',
    default_columns: ['reason', 'adjustment_count', 'quantity', 'value'],
  },
  {
    key: 'inventory_reorder',
    label: 'Inventory reorder levels',
    category: 'inventory',
    description:
      'reorder_level and reorder_quantity = max(0, reorder_level − quantity).',
    visualization: 'TABLE',
    default_columns: [
      'facility',
      'inventory_item',
      'quantity',
      'reorder_level',
      'reorder_quantity',
      'risk_state',
    ],
  },
  {
    key: 'inventory_stock_turnover',
    label: 'Stock turnover',
    category: 'inventory',
    description:
      'Issued qty / average on-hand; days_of_stock = period_days / turnover.',
    visualization: 'BAR_CHART',
    default_columns: [
      'inventory_item',
      'facility',
      'issued_quantity',
      'stock_turnover',
      'days_of_stock',
    ],
  },
  {
    key: 'inventory_stock_velocity',
    label: 'Stock velocity',
    category: 'inventory',
    description:
      'Fast/slow/dead classification from OUTBOUND+DISPENSE vs on-hand.',
    visualization: 'TABLE',
    default_columns: [
      'facility',
      'inventory_item',
      'quantity',
      'issued_quantity',
      'velocity_class',
    ],
  },
  {
    key: 'inventory_stock_movement_history',
    label: 'Stock movement history',
    category: 'inventory',
    description: 'Chronological stock_movement rows for the selected period.',
    visualization: 'TABLE',
    default_columns: [
      'occurred_at',
      'movement_type',
      'reason',
      'quantity',
      'facility',
      'inventory_item',
    ],
  },
  {
    key: 'pharmacy_medicines_catalog',
    label: 'Pharmacy medicines catalog',
    category: 'pharmacy',
    description:
      'Drug / batch catalog attributes (name, form, strength, prices, margins, lots, storage). Barcode and controlled status are schema gaps.',
    visualization: 'TABLE',
    default_columns: [
      'row_kind',
      'drug_id',
      'name',
      'code',
      'human_friendly_id',
      'generic_name',
      'brand_name',
      'category',
      'strength',
      'form',
      'dosage_form',
      'unit',
      'batch_number',
      'quantity',
      'manufactured_at',
      'expiry_date',
      'days_to_expiry',
      'selling_price',
      'unit_price',
      'purchase_price',
      'buy_unit_price',
      'profit_per_unit',
      'profit_margin',
      'currency',
      'storage_room',
      'storage_shelf',
      'storage_requirements',
    ],
  },
  {
    key: 'pharmacy_purchase_orders',
    label: 'Pharmacy purchase orders',
    category: 'pharmacy',
    description:
      'Header-only purchase_order rows with supplier, goods_receipt delivery_days, and shared 7-day SLA reliability/late metrics. No PO line amounts.',
    visualization: 'TABLE',
    default_columns: [
      'ordered_at',
      'status',
      'supplier',
      'human_friendly_id',
      'received_at',
      'delivery_days',
    ],
  },
  {
    key: 'pharmacy_purchase_inbound_value',
    label: 'Pharmacy purchase inbound value',
    category: 'pharmacy',
    description:
      'INBOUND+PURCHASE stock_movement quantity × drug.buy_unit_price (stock inbound cost basis until PO lines exist).',
    visualization: 'TABLE',
    default_columns: [
      'occurred_at',
      'supplier',
      'inventory_item',
      'quantity',
      'amount',
      'currency',
      'cost_basis',
    ],
  },
  {
    key: 'pharmacy_purchases_by_supplier',
    label: 'Pharmacy purchases by supplier',
    category: 'pharmacy',
    description:
      'PO counts plus inbound purchase value (INBOUND×buy_unit_price) grouped by supplier.',
    visualization: 'BAR_CHART',
    default_columns: [
      'supplier',
      'po_count',
      'quantity',
      'amount',
      'currency',
    ],
  },
  {
    key: 'pharmacy_supplier_pricing',
    label: 'Pharmacy supplier pricing',
    category: 'pharmacy',
    description: 'Current drug.buy_unit_price grouped by drug.supplier_id.',
    visualization: 'TABLE',
    default_columns: ['supplier', 'drug', 'buy_unit_price', 'currency'],
  },
  {
    key: 'pharmacy_purchase_returns',
    label: 'Pharmacy purchase returns',
    category: 'pharmacy',
    description:
      'OUTBOUND+RETURN stock_movement rows (purchase-return-to-supplier proxy).',
    visualization: 'TABLE',
    default_columns: [
      'occurred_at',
      'inventory_item',
      'quantity',
      'facility',
      'reason',
    ],
  },
  {
    key: 'pharmacy_drug_price_changes',
    label: 'Pharmacy drug price changes',
    category: 'pharmacy',
    description:
      'audit_log UPDATE rows on drug with buy_unit_price / unit_price diffs.',
    visualization: 'TABLE',
    default_columns: [
      'changed_at',
      'drug',
      'field',
      'from_value',
      'to_value',
      'currency',
    ],
  },
  {
    key: 'hr_staffing_leave_coverage',
    label: 'HR staffing and leave coverage',
    category: 'hr',
    description: 'Staffing availability, leave pressure, and shift assignment gaps.',
    visualization: 'BAR_CHART',
    default_columns: ['metric', 'value', 'facility'],
  },
  {
    key: 'biomedical_incidents_downtime',
    label: 'Biomedical incidents and downtime',
    category: 'biomedical',
    description: 'Open incident volume, critical downtime, and service-risk indicators.',
    visualization: 'LINE_CHART',
    default_columns: ['metric', 'value', 'facility'],
  },
  {
    key: 'communications_delivery_performance',
    label: 'Communications delivery performance',
    category: 'communications',
    description: 'Channel delivery success and failure distribution.',
    visualization: 'DONUT_CHART',
    default_columns: ['channel', 'status', 'deliveries'],
  },
]);

const REPORT_DATASET_MAP = Object.freeze(
  REPORT_DATASETS.reduce((acc, dataset) => {
    acc[dataset.key] = dataset;
    return acc;
  }, {})
);

const REPORT_OVERVIEW_DATASET_KEYS = Object.freeze(REPORT_DATASETS.map((dataset) => dataset.key));

module.exports = {
  ANALYTICS_EVENT_SEVERITIES,
  KPI_THRESHOLD_STATES,
  REPORT_DATASETS,
  REPORT_DATASET_MAP,
  REPORT_DEFINITION_STATUSES,
  REPORT_DEFAULT_RETENTION_DAYS,
  REPORT_FORMATS,
  REPORT_OVERVIEW_DATASET_KEYS,
  REPORT_PANELS,
  REPORT_RESOURCES,
  REPORT_RESOURCE_BY_PANEL,
  REPORT_RUNNER_MAX_CONCURRENCY,
  REPORT_RUNNER_POLL_INTERVAL_MS,
  REPORT_RUN_STATUSES,
  REPORT_SCHEDULE_FREQUENCIES,
  REPORT_SCHEDULE_LEASE_MS,
  REPORT_SCHEDULE_STATUSES,
  REPORT_TRIGGER_TYPES,
  REPORT_WIDGET_TYPES,
};
