const DEMO_PLAN_CATALOG = Object.freeze([
  {
    code: 'free',
    name: 'Free',
    tier_code: 'FREE',
    price: 0,
    billing_cycle: 'MONTHLY',
    max_users: 1,
    max_facilities: 1,
    max_storage_mb: 200,
    max_modules: 8,
    extension_json: {
      price_notes: { monthly: 0 },
      usage_limits: { new_patients_per_day: 5 },
      support: 'best_effort',
    },
  },
  {
    code: 'basic',
    name: 'Basic',
    tier_code: 'BASIC',
    price: 39,
    billing_cycle: 'MONTHLY',
    max_users: 5,
    max_facilities: 1,
    max_storage_mb: 5120,
    max_modules: 20,
    extension_json: {
      price_notes: { monthly: 39, yearly: 390, extra_user_monthly: 6, extra_user_yearly: 60 },
      branch_allowance: { included_branches: 2 },
      support: 'email_48_72h',
    },
  },
  {
    code: 'pro',
    name: 'Pro',
    tier_code: 'PRO',
    price: 89,
    billing_cycle: 'MONTHLY',
    max_users: 10,
    max_facilities: 3,
    max_storage_mb: 20480,
    max_modules: 80,
    extension_json: {
      price_notes: {
        monthly: 89,
        yearly: 890,
        extra_user_monthly: 8,
        extra_user_yearly: 80,
        extra_facility_monthly: 15,
        extra_facility_yearly: 150,
      },
      support: 'priority_24_48h',
    },
  },
  {
    code: 'advanced',
    name: 'Advanced',
    tier_code: 'ADVANCED',
    price: 600,
    billing_cycle: 'YEARLY',
    max_users: 300,
    max_facilities: 50,
    max_storage_mb: 102400,
    max_modules: 160,
    extension_json: {
      commercial_terms: {
        setup_range_usd: [2500, 7500],
        annual_maintenance_range_usd: [600, 1500],
        hosting_model: 'on_prem_standard',
      },
      support: 'priority_optional_sla',
    },
  },
  {
    code: 'custom',
    name: 'Custom',
    tier_code: 'CUSTOM',
    price: 10000,
    billing_cycle: 'YEARLY',
    max_users: null,
    max_facilities: null,
    max_storage_mb: null,
    max_modules: null,
    extension_json: {
      commercial_terms: {
        setup_from_usd: 10000,
        annual_support_percent_range: [15, 25],
        hosting_model: 'cloud_on_prem_hybrid',
        contracting_model: 'sow',
      },
      support: 'dedicated_custom_sla',
    },
  },
]);

const DEMO_ADD_ON_CATALOG = Object.freeze([
  {
    code: 'inventory_procurement_lite',
    slug: 'inventory-procurement-lite',
    name: 'Inventory and Procurement Lite',
    module_group: 11,
    minimum_plan_tier_code: 'BASIC',
    add_on_price: 39,
    add_on_billing_cycle: 'MONTHLY',
    extension_json: { price_range_usd_monthly: [19, 59] },
  },
  {
    code: 'biomedical_engineering_suite',
    slug: 'biomedical-engineering-suite',
    name: 'Biomedical Engineering Suite',
    module_group: 15,
    minimum_plan_tier_code: 'PRO',
    add_on_price: 129,
    add_on_billing_cycle: 'MONTHLY',
    extension_json: { price_range_usd_monthly: [49, 199] },
  },
  {
    code: 'compliance_audit_suite',
    slug: 'compliance-audit-suite',
    name: 'Compliance and Audit Suite',
    module_group: 19,
    minimum_plan_tier_code: 'PRO',
    add_on_price: 89,
    add_on_billing_cycle: 'MONTHLY',
    extension_json: { price_range_usd_monthly: [39, 149] },
  },
  {
    code: 'advanced_analytics',
    slug: 'advanced-analytics',
    name: 'Advanced Analytics',
    module_group: 17,
    minimum_plan_tier_code: 'PRO',
    add_on_price: 59,
    add_on_billing_cycle: 'MONTHLY',
    extension_json: { price_range_usd_monthly: [29, 99] },
  },
  {
    code: 'integrations_webhooks_pack',
    slug: 'integrations-webhooks-pack',
    name: 'Integrations/Webhooks Pack',
    module_group: 20,
    minimum_plan_tier_code: 'PRO',
    add_on_price: 79,
    add_on_billing_cycle: 'MONTHLY',
    extension_json: { price_range_usd_monthly: [49, 149] },
  },
  {
    code: 'extra_storage',
    slug: 'extra-storage',
    name: 'Extra Storage',
    module_group: 17,
    minimum_plan_tier_code: 'BASIC',
    add_on_price: 5,
    add_on_billing_cycle: 'MONTHLY',
    extension_json: { billing_basis: 'per_10gb' },
  },
  {
    code: 'sms_credits',
    slug: 'sms-credits',
    name: 'SMS Credits',
    module_group: 16,
    minimum_plan_tier_code: 'BASIC',
    add_on_price: 0,
    add_on_billing_cycle: 'MONTHLY',
    extension_json: { billing_basis: 'usage_based' },
  },
]);

const DEMO_CORE_MODULE_CATALOG = Object.freeze([
  { code: 'auth_rbac_basics', slug: 'auth-rbac-basics', name: 'Auth and RBAC Basics', module_group: 1, minimum_plan_tier_code: 'FREE' },
  { code: 'patient_registry', slug: 'patient-registry', name: 'Patient Registry and Consent', module_group: 2, minimum_plan_tier_code: 'FREE' },
  { code: 'scheduling_queue', slug: 'scheduling-queue', name: 'Scheduling and Queue', module_group: 3, minimum_plan_tier_code: 'FREE' },
  { code: 'encounters_vitals', slug: 'encounters-vitals', name: 'Encounters and Vitals', module_group: 4, minimum_plan_tier_code: 'FREE' },
  { code: 'inpatient_bed_management', slug: 'inpatient-bed-management', name: 'IPD and Bed Management', module_group: 5, minimum_plan_tier_code: 'PRO' },
  { code: 'icu_critical_care', slug: 'icu-critical-care', name: 'ICU and Critical Care', module_group: 6, minimum_plan_tier_code: 'PRO' },
  { code: 'theatre_anesthesia', slug: 'theatre-anesthesia', name: 'Theatre and Anesthesia', module_group: 7, minimum_plan_tier_code: 'PRO' },
  { code: 'lab_workflows', slug: 'lab-workflows', name: 'Lab Workflows', module_group: 8, minimum_plan_tier_code: 'PRO' },
  { code: 'radiology_workflows', slug: 'radiology-workflows', name: 'Radiology Workflows', module_group: 9, minimum_plan_tier_code: 'PRO' },
  { code: 'pharmacy_dispensing', slug: 'pharmacy-dispensing', name: 'Pharmacy Dispensing', module_group: 10, minimum_plan_tier_code: 'PRO' },
  { code: 'mortuary_operations', slug: 'mortuary', name: 'Mortuary', module_group: 12, minimum_plan_tier_code: 'BASIC' },
  { code: 'billing_insurance', slug: 'billing-insurance', name: 'Billing, Payments, and Insurance', module_group: 13, minimum_plan_tier_code: 'FREE' },
  { code: 'hr_rosters', slug: 'hr-rosters', name: 'HR and Rosters', module_group: 14, minimum_plan_tier_code: 'PRO' },
  { code: 'facilities_maintenance', slug: 'facilities-maintenance', name: 'Facilities and Maintenance', module_group: 15, minimum_plan_tier_code: 'BASIC' },
  { code: 'notifications_communications', slug: 'notifications-communications', name: 'Notifications and Communications', module_group: 16, minimum_plan_tier_code: 'FREE' },
  { code: 'reporting_analytics', slug: 'reporting-analytics', name: 'Reporting and Analytics', module_group: 17, minimum_plan_tier_code: 'BASIC' },
  { code: 'subscription_controls', slug: 'subscription-controls', name: 'Subscription and Licensing Controls', module_group: 18, minimum_plan_tier_code: 'FREE' },
  { code: 'compliance_audit_core', slug: 'compliance-audit-core', name: 'Compliance and Audit Core', module_group: 19, minimum_plan_tier_code: 'ADVANCED' },
  { code: 'integrations_core', slug: 'integrations-core', name: 'Integrations and Webhooks', module_group: 20, minimum_plan_tier_code: 'ADVANCED' },
]);

const DEMO_ROLE_CODES = Object.freeze([
  'SUPER_ADMIN',
  'TENANT_ADMIN',
  'FACILITY_ADMIN',
  'DOCTOR',
  'NURSE',
  'LAB_TECH',
  'PHARMACIST',
  'RECEPTIONIST',
  'BILLING',
  'OPERATIONS',
  'HR',
  'BIOMED',
  'HOUSE_KEEPER',
  'AMBULANCE_OPERATOR',
  'UNIT_MANAGER',
  'WARD_MANAGER',
  'ICU_MANAGER',
  'THEATRE_MANAGER',
  'HOUSEKEEPING_MANAGER',
  'BIOMED_MANAGER',
  'MORTUARY_STAFF',
  'MORTUARY_MANAGER',
  'PATIENT',
]);

const DEMO_PERMISSION_CATALOG = Object.freeze([
  'subscriptions.manage',
  'communications.manage',
  'patients.manage',
  'diagnostics.manage',
  'billing.manage',
  'biomedical.manage',
  'compliance.manage',
  'integrations.manage',
]);

const DEMO_TENANTS = Object.freeze([
  {
    key: 'demo',
    scenario_key: 'DEMO',
    tenant_code: 'DEMO',
    name: 'DemoCare General Hospital',
    slug: 'democare-general-hospital',
    primary_plan_code: 'advanced',
    seed_inpatient_resources: true,
    facilities: [{ key: 'main', name: 'DemoCare General Hospital', type: 'HOSPITAL' }],
    branches: [],
    departments: [
      'Outpatient',
      'Inpatient',
      'Emergency',
      'Laboratory',
      'Radiology',
      'Pharmacy',
      'Billing',
      'Operations',
      'Biomedical',
      'Front Office',
      'Compliance',
      'Support Services',
      'Mortuary',
    ],
    users: [
      { key: 'superadmin', role: 'SUPER_ADMIN', email: 'super.admin@hosspi.com', first_name: 'Platform', last_name: 'Demo', title: 'Platform Administrator' },
      { key: 'tenant_admin', role: 'TENANT_ADMIN', email: 'tenant.admin@hosspi.com', first_name: 'Taylor', last_name: 'Demo', title: 'Hospital Administrator', extra_roles: ['UNIT_MANAGER'] },
      { key: 'facility_admin', role: 'FACILITY_ADMIN', email: 'facility.admin@hosspi.com', first_name: 'Morgan', last_name: 'Demo', title: 'Facility Administrator' },
      { key: 'doctor', role: 'DOCTOR', email: 'doctor@hosspi.com', first_name: 'Jordan', last_name: 'Demo', title: 'Consultant Physician', extra_roles: ['THEATRE_MANAGER'] },
      { key: 'nurse', role: 'NURSE', email: 'nurse@hosspi.com', first_name: 'Casey', last_name: 'Demo', title: 'Registered Nurse', extra_roles: ['WARD_MANAGER', 'ICU_MANAGER'] },
      { key: 'lab', role: 'LAB_TECH', email: 'lab@hosspi.com', first_name: 'Riley', last_name: 'Demo', title: 'Laboratory Technologist' },
      { key: 'pharmacy', role: 'PHARMACIST', email: 'pharmacy@hosspi.com', first_name: 'Harper', last_name: 'Demo', title: 'Pharmacist' },
      { key: 'reception', role: 'RECEPTIONIST', email: 'reception@hosspi.com', first_name: 'Skyler', last_name: 'Demo', title: 'Front Desk Officer' },
      { key: 'billing', role: 'BILLING', email: 'billing@hosspi.com', first_name: 'Rowan', last_name: 'Demo', title: 'Billing Officer' },
      { key: 'operations', role: 'OPERATIONS', email: 'operations@hosspi.com', first_name: 'Parker', last_name: 'Demo', title: 'Operations Lead' },
      { key: 'hr', role: 'HR', email: 'hr@hosspi.com', first_name: 'Quinn', last_name: 'Demo', title: 'HR Officer' },
      { key: 'biomed', role: 'BIOMED', email: 'biomed@hosspi.com', first_name: 'Avery', last_name: 'Demo', title: 'Biomedical Engineer', extra_roles: ['BIOMED_MANAGER'] },
      { key: 'house_keeper', role: 'HOUSE_KEEPER', email: 'housekeeping@hosspi.com', first_name: 'Dakota', last_name: 'Demo', title: 'Housekeeping Supervisor', extra_roles: ['HOUSEKEEPING_MANAGER'] },
      { key: 'mortuary_staff', role: 'MORTUARY_STAFF', email: 'mortuary.staff@hosspi.com', first_name: 'Taylor', last_name: 'Mortuary', title: 'Mortuary Officer' },
      { key: 'mortuary_manager', role: 'MORTUARY_MANAGER', email: 'mortuary.manager@hosspi.com', first_name: 'Jordan', last_name: 'Mortuary', title: 'Mortuary Manager' },
      { key: 'ambulance', role: 'AMBULANCE_OPERATOR', email: 'ambulance@hosspi.com', first_name: 'Reese', last_name: 'Demo', title: 'Ambulance Operator' },
      { key: 'patient', role: 'PATIENT', email: 'patient.portal@hosspi.com', first_name: 'Patient', last_name: 'Demo', title: 'Patient Portal User' },
    ],
  },
]);

const DEMO_TENANT = DEMO_TENANTS[0];

const CURATED_MODELS = Object.freeze(new Set([
  'tenant',
  'facility',
  'branch',
  'department',
  'ward',
  'room',
  'bed',
  'address',
  'contact',
  'role',
  'permission',
  'role_permission',
  'user',
  'user_profile',
  'user_role',
  'patient',
  'appointment',
  'encounter',
  'diagnosis',
  'vital_sign',
  'admission',
  'lab_test',
  'lab_order',
  'lab_order_item',
  'lab_sample',
  'lab_result',
  'radiology_test',
  'radiology_order',
  'radiology_result',
  'drug',
  'pharmacy_order',
  'pharmacy_order_item',
  'dispense_log',
  'inventory_item',
  'inventory_stock',
  'supplier',
  'purchase_request',
  'purchase_order',
  'goods_receipt',
  'emergency_case',
  'triage_assessment',
  'ambulance',
  'ambulance_dispatch',
  'ambulance_trip',
  'invoice',
  'invoice_item',
  'payment',
  'refund',
  'billing_adjustment',
  'staff_position',
  'staff_profile',
  'shift',
  'shift_assignment',
  'nurse_roster',
  'housekeeping_task',
  'maintenance_request',
  'equipment_category',
  'equipment_registry',
  'equipment_maintenance_plan',
  'equipment_work_order',
  'equipment_calibration_log',
  'equipment_safety_test_log',
  'equipment_downtime_log',
  'equipment_spare_part',
  'equipment_incident_report',
  'equipment_recall_notice',
  'equipment_utilization_snapshot',
  'equipment_disposal_transfer',
  'unit_management_assignment',
  'mortuary_deceased_profile',
  'mortuary_case',
  'mortuary_storage_unit',
  'mortuary_storage_slot',
  'mortuary_storage_assignment',
  'mortuary_custody_event',
  'mortuary_viewing',
  'mortuary_post_mortem_request',
  'mortuary_release_authorisation',
  'mortuary_billable_event',
  'notification',
  'notification_delivery',
  'conversation',
  'message',
  'conversation_participant',
  'conversation_visibility_role',
  'message_attachment',
  'template',
  'template_variable',
  'subscription_plan',
  'subscription',
  'subscription_invoice',
  'module',
  'module_subscription',
  'license',
  'configuration_snapshot',
  'audit_log',
  'phi_access_log',
  'data_processing_log',
  'breach_notification',
  'system_change_log',
  'abac_policy',
  'break_glass_access',
  'break_glass_review',
  'office_context',
  'shift_close',
  'day_close',
  'handover',
  'custody_snapshot',
  'closeout_pack',
  'integration',
  'integration_log',
  'webhook_subscription',
]));

module.exports = {
  CURATED_MODELS,
  DEMO_ADD_ON_CATALOG,
  DEMO_CORE_MODULE_CATALOG,
  DEMO_PERMISSION_CATALOG,
  DEMO_PLAN_CATALOG,
  DEMO_ROLE_CODES,
  DEMO_TENANT,
  DEMO_TENANTS,
};
