const DEMO_PLAN_TIER_ORDER = Object.freeze({
  free: 0,
  basic: 1,
  advanced: 2,
  pro: 3,
  custom: 4,
  developer: 5,
});

const DEMO_PLAN_CATALOG = Object.freeze([
  {
    code: 'free',
    name: 'Free',
    tier_code: 'FREE',
    price: 0,
    billing_cycle: 'MONTHLY',
    max_users: 1,
    max_facilities: 1,
    max_storage_mb: 200,
    max_modules: 16,
    extension_json: {
      price_notes: { monthly: 0 },
      usage_limits: { new_patients_per_day: 5 },
      support: 'best_effort',
    },
  },
  {
    code: 'basic',
    name: 'Basic',
    tier_code: 'BASIC',
    price: 39,
    billing_cycle: 'MONTHLY',
    max_users: 5,
    max_facilities: 1,
    max_storage_mb: 5120,
    max_modules: 20,
    extension_json: {
      price_notes: { monthly: 39, yearly: 390, extra_user_monthly: 6, extra_user_yearly: 60 },
      support: 'email_48_72h',
    },
  },
  {
    code: 'pro',
    name: 'Pro',
    tier_code: 'PRO',
    price: 89,
    billing_cycle: 'MONTHLY',
    max_users: 10,
    max_facilities: 3,
    max_storage_mb: 20480,
    max_modules: 80,
    extension_json: {
      price_notes: {
        monthly: 89,
        yearly: 890,
        extra_user_monthly: 8,
        extra_user_yearly: 80,
        extra_facility_monthly: 15,
        extra_facility_yearly: 150,
      },
      support: 'priority_24_48h',
    },
  },
  {
    code: 'advanced',
    name: 'Advanced',
    tier_code: 'ADVANCED',
    price: 600,
    billing_cycle: 'YEARLY',
    max_users: 300,
    max_facilities: 50,
    max_storage_mb: 102400,
    max_modules: 160,
    extension_json: {
      commercial_terms: {
        setup_range_usd: [2500, 7500],
        annual_maintenance_range_usd: [600, 1500],
        hosting_model: 'on_prem_standard',
      },
      support: 'priority_optional_sla',
    },
  },
  {
    code: 'custom',
    name: 'Custom',
    tier_code: 'CUSTOM',
    price: 10000,
    billing_cycle: 'YEARLY',
    max_users: null,
    max_facilities: null,
    max_storage_mb: null,
    max_modules: null,
    extension_json: {
      commercial_terms: {
        setup_from_usd: 10000,
        annual_support_percent_range: [15, 25],
        hosting_model: 'cloud_on_prem_hybrid',
        contracting_model: 'sow',
      },
      support: 'dedicated_custom_sla',
    },
  },
  {
    code: 'developer',
    name: 'Developer',
    tier_code: 'DEVELOPER',
    price: 0,
    billing_cycle: 'YEARLY',
    max_users: null,
    max_facilities: null,
    max_storage_mb: null,
    max_modules: null,
    extension_json: {
      commercial_terms: {
        hosting_model: 'sandbox',
        contracting_model: 'internal_dev',
      },
      support: 'engineering',
      is_developer_plan: true,
      includes_all_modules: true,
    },
  },
].sort(
  (left, right) =>
    DEMO_PLAN_TIER_ORDER[left.code] - DEMO_PLAN_TIER_ORDER[right.code]
));

// Optional paid add-ons beyond the included Advanced/Custom matrix.
const DEMO_ADD_ON_CATALOG = Object.freeze([
  {
    code: 'compliance_audit_suite',
    slug: 'compliance-audit-suite',
    name: 'Compliance and Audit Suite',
    module_group: 19,
    minimum_plan_tier_code: 'CUSTOM',
    add_on_price: 89,
    add_on_billing_cycle: 'MONTHLY',
    extension_json: { price_range_usd_monthly: [39, 149] },
  },
  {
    code: 'integrations_webhooks_pack',
    slug: 'integrations-webhooks-pack',
    name: 'Integrations/Webhooks Pack',
    module_group: 20,
    minimum_plan_tier_code: 'CUSTOM',
    add_on_price: 79,
    add_on_billing_cycle: 'MONTHLY',
    extension_json: { price_range_usd_monthly: [49, 149] },
  },
]);

const {
  COMMERCIAL_MODULE_MATRIX,
  PLATFORM_INFRASTRUCTURE_MODULES,
} = require('../../src/lib/subscriptions/plan-module-matrix');

const DEMO_CORE_MODULE_CATALOG = Object.freeze([
  ...PLATFORM_INFRASTRUCTURE_MODULES.map((entry) => ({
    ...entry,
    is_add_on: false,
  })),
  ...COMMERCIAL_MODULE_MATRIX.map((entry) => ({
    ...entry,
    is_add_on: false,
  })),
]);

const DEMO_ROLE_CODES = Object.freeze([
  'PLATFORM_OWNER',
  'PLATFORM_ADMIN',
  'TENANT_ADMIN',
  'FACILITY_ADMIN',
  'INTEGRATION_ADMIN',
  'HR_STAFF',
  'OPERATIONS_STAFF',
  'DISCHARGE_PLANNER',
  'DENTIST',
  'RADIOLOGIST',
  'SONOGRAPHER',
  'ACCOUNTANT',
  'SUPPORT_STAFF',
  'VISITOR_GUEST',
  'DOCTOR',
  'OPD_DOCTOR',
  'ICU_DOCTOR',
  'ATTENDING_PHYSICIAN',
  'RESIDENT_PHYSICIAN',
  'SURGEON',
  'ANESTHESIOLOGIST',
  'PHYSICIAN_ASSISTANT',
  'EMERGENCY_PHYSICIAN',
  'NURSE',
  'LICENSED_PRACTICAL_NURSE',
  'NURSE_PRACTITIONER',
  'TRIAGE_NURSE',
  'MIDWIFE',
  'CHARGE_NURSE',
  'LAB_TECH',
  'MEDICAL_LABORATORY_SCIENTIST',
  'PATHOLOGIST',
  'RADIOLOGY_TECH',
  'PHARMACIST',
  'PHARMACY_TECHNICIAN',
  'PHARMACY_BILLING',
  'RECEPTIONIST',
  'ADMISSIONS_COORDINATOR',
  'MEDICAL_RECORDS_CLERK',
  'BILLING',
  'MEDICAL_CODER',
  'OPERATIONS',
  'HR',
  'BIOMED',
  'HOUSE_KEEPER',
  'AMBULANCE_OPERATOR',
  'PARAMEDIC',
  'EMT',
  'PHYSIOTHERAPIST',
  'OCCUPATIONAL_THERAPIST',
  'RESPIRATORY_THERAPIST',
  'DIETITIAN',
  'SOCIAL_WORKER',
  'CLINICAL_PSYCHOLOGIST',
  'UNIT_MANAGER',
  'WARD_MANAGER',
  'ICU_MANAGER',
  'THEATRE_MANAGER',
  'HOUSEKEEPING_MANAGER',
  'BIOMED_MANAGER',
  'MORTUARY_STAFF',
  'MORTUARY_MANAGER',
  'PATIENT',
]);

// Permissions are seeded from the canonical catalog (`@config/permissions`) in
// seed-access-pack.js. A second, dot-notation list used to live here; it was
// unreachable and violated the `resource:action` key format in permissions.mdc.

const DEMO_TENANTS = Object.freeze([
  {
    key: 'demo',
    scenario_key: 'DEMO',
    tenant_code: 'DEMO',
    name: 'DemoCare General Hospital',
    slug: 'democare-general-hospital',
    primary_plan_code: 'pro',
    seed_inpatient_resources: true,
    facilities: [
      { key: 'main', name: 'DemoCare General Hospital', type: 'HOSPITAL' },
      // Second facility for stock transfer sending/receiving + branch comparison.
      { key: 'annex', name: 'DemoCare Annex Pharmacy', type: 'CLINIC' },
    ],
    // Pro plan allows ≤3 facilities. Annex carries transfer receive legs and light stock.
    // verify-demo-data accepts all demo-tenant facility ids for ownership checks.
    departments: [
      'Outpatient',
      'Inpatient',
      'Emergency',
      'Laboratory',
      'Radiology',
      'Pharmacy',
      'Billing',
      'Operations',
      'Biomedical',
      'Front Office',
      'Compliance',
      'Support Services',
      'Mortuary',
      'Human Resources',
    ],
    users: [
      { key: 'platform_owner', role: 'PLATFORM_OWNER', email: 'platform.owner@hosspi.com', first_name: 'Owner', last_name: 'Demo', title: 'Platform Owner' },
      { key: 'platform_admin', role: 'PLATFORM_ADMIN', email: 'platform.admin@hosspi.com', first_name: 'Platform', last_name: 'Demo', title: 'Platform Administrator' },
      { key: 'tenant_admin', role: 'TENANT_ADMIN', email: 'tenant.admin@hosspi.com', first_name: 'Taylor', last_name: 'Demo', title: 'Hospital Administrator', extra_roles: ['UNIT_MANAGER'] },
      { key: 'facility_admin', role: 'FACILITY_ADMIN', email: 'facility.admin@hosspi.com', first_name: 'Morgan', last_name: 'Demo', title: 'Facility Administrator' },
      { key: 'integration_admin', role: 'INTEGRATION_ADMIN', email: 'integration.admin@hosspi.com', first_name: 'Indigo', last_name: 'Demo', title: 'Integration Administrator' },
      { key: 'hr_staff', role: 'HR_STAFF', email: 'hr.staff@hosspi.com', first_name: 'Hayden', last_name: 'Demo', title: 'HR Staff' },
      { key: 'operations_staff', role: 'OPERATIONS_STAFF', email: 'operations.staff@hosspi.com', first_name: 'Oakley', last_name: 'Demo', title: 'Operations Staff' },
      { key: 'discharge_planner', role: 'DISCHARGE_PLANNER', email: 'discharge@hosspi.com', first_name: 'Drew', last_name: 'Demo', title: 'Discharge Planner' },
      { key: 'dentist', role: 'DENTIST', email: 'dentist@hosspi.com', first_name: 'Devon', last_name: 'Demo', title: 'Dentist' },
      { key: 'radiologist', role: 'RADIOLOGIST', email: 'radiologist@hosspi.com', first_name: 'Remy', last_name: 'Demo', title: 'Radiologist' },
      { key: 'sonographer', role: 'SONOGRAPHER', email: 'sonographer@hosspi.com', first_name: 'Sage', last_name: 'Demo', title: 'Sonographer' },
      { key: 'accountant', role: 'ACCOUNTANT', email: 'accountant@hosspi.com', first_name: 'Alex', last_name: 'Demo', title: 'Accountant' },
      { key: 'support_staff', role: 'SUPPORT_STAFF', email: 'support@hosspi.com', first_name: 'Sam', last_name: 'Demo', title: 'Support Staff' },
      { key: 'visitor_guest', role: 'VISITOR_GUEST', email: 'visitor@hosspi.com', first_name: 'Vic', last_name: 'Demo', title: 'Visitor Guest' },
      { key: 'doctor', role: 'DOCTOR', email: 'doctor@hosspi.com', first_name: 'Jordan', last_name: 'Demo', title: 'Consultant Physician' },
      { key: 'opd_doctor', role: 'OPD_DOCTOR', email: 'opd.doctor@hosspi.com', first_name: 'Owen', last_name: 'Demo', title: 'OPD Doctor' },
      { key: 'icu_doctor', role: 'ICU_DOCTOR', email: 'icu.doctor@hosspi.com', first_name: 'Iris', last_name: 'Demo', title: 'ICU Doctor' },
      { key: 'attending_physician', role: 'ATTENDING_PHYSICIAN', email: 'attending@hosspi.com', first_name: 'Avery', last_name: 'Attending', title: 'Attending Physician' },
      { key: 'resident_physician', role: 'RESIDENT_PHYSICIAN', email: 'resident@hosspi.com', first_name: 'Robin', last_name: 'Demo', title: 'Resident Physician' },
      { key: 'surgeon', role: 'SURGEON', email: 'surgeon@hosspi.com', first_name: 'Sydney', last_name: 'Demo', title: 'Surgeon' },
      { key: 'anesthesiologist', role: 'ANESTHESIOLOGIST', email: 'anesthesia@hosspi.com', first_name: 'Ash', last_name: 'Demo', title: 'Anesthesiologist' },
      { key: 'physician_assistant', role: 'PHYSICIAN_ASSISTANT', email: 'pa@hosspi.com', first_name: 'Pat', last_name: 'Demo', title: 'Physician Assistant' },
      { key: 'emergency_physician', role: 'EMERGENCY_PHYSICIAN', email: 'er.doctor@hosspi.com', first_name: 'Eden', last_name: 'Demo', title: 'Emergency Physician' },
      { key: 'nurse', role: 'NURSE', email: 'nurse@hosspi.com', first_name: 'Casey', last_name: 'Demo', title: 'Registered Nurse', extra_roles: ['WARD_MANAGER', 'ICU_MANAGER'] },
      { key: 'lpn', role: 'LICENSED_PRACTICAL_NURSE', email: 'lpn@hosspi.com', first_name: 'Leslie', last_name: 'Demo', title: 'Licensed Practical Nurse' },
      { key: 'nurse_practitioner', role: 'NURSE_PRACTITIONER', email: 'np@hosspi.com', first_name: 'Nora', last_name: 'Demo', title: 'Nurse Practitioner' },
      { key: 'triage_nurse', role: 'TRIAGE_NURSE', email: 'triage@hosspi.com', first_name: 'Tessa', last_name: 'Demo', title: 'Triage Nurse' },
      { key: 'midwife', role: 'MIDWIFE', email: 'midwife@hosspi.com', first_name: 'Mia', last_name: 'Demo', title: 'Midwife' },
      { key: 'charge_nurse', role: 'CHARGE_NURSE', email: 'charge.nurse@hosspi.com', first_name: 'Charlie', last_name: 'Demo', title: 'Charge Nurse' },
      { key: 'lab', role: 'LAB_TECH', email: 'lab@hosspi.com', first_name: 'Riley', last_name: 'Demo', title: 'Laboratory Technologist' },
      { key: 'mls', role: 'MEDICAL_LABORATORY_SCIENTIST', email: 'mls@hosspi.com', first_name: 'Miles', last_name: 'Demo', title: 'Medical Laboratory Scientist' },
      { key: 'pathologist', role: 'PATHOLOGIST', email: 'pathologist@hosspi.com', first_name: 'Paige', last_name: 'Demo', title: 'Pathologist' },
      { key: 'radiology', role: 'RADIOLOGY_TECH', email: 'radiology@hosspi.com', first_name: 'Emery', last_name: 'Demo', title: 'Radiology Technologist' },
      { key: 'pharmacy', role: 'PHARMACIST', email: 'pharmacy@hosspi.com', first_name: 'Harper', last_name: 'Demo', title: 'Pharmacist' },
      { key: 'pharmacy2', role: 'PHARMACIST', email: 'pharmacy2@hosspi.com', first_name: 'Morgan', last_name: 'Demo', title: 'Pharmacist' },
      { key: 'pharmacy_tech', role: 'PHARMACY_TECHNICIAN', email: 'pharmacy.tech@hosspi.com', first_name: 'Phoenix', last_name: 'Demo', title: 'Pharmacy Technician' },
      { key: 'pharmacy_billing', role: 'PHARMACY_BILLING', email: 'pharmacy.billing@hosspi.com', first_name: 'Blair', last_name: 'Demo', title: 'Pharmacy Billing' },
      { key: 'reception', role: 'RECEPTIONIST', email: 'reception@hosspi.com', first_name: 'Skyler', last_name: 'Demo', title: 'Front Desk Officer' },
      { key: 'admissions', role: 'ADMISSIONS_COORDINATOR', email: 'admissions@hosspi.com', first_name: 'Addison', last_name: 'Demo', title: 'Admissions Coordinator' },
      { key: 'medical_records', role: 'MEDICAL_RECORDS_CLERK', email: 'records@hosspi.com', first_name: 'Reese', last_name: 'Records', title: 'Medical Records Clerk' },
      { key: 'billing', role: 'BILLING', email: 'billing@hosspi.com', first_name: 'Rowan', last_name: 'Demo', title: 'Billing Officer' },
      { key: 'medical_coder', role: 'MEDICAL_CODER', email: 'coder@hosspi.com', first_name: 'Cody', last_name: 'Demo', title: 'Medical Coder' },
      { key: 'operations', role: 'OPERATIONS', email: 'operations@hosspi.com', first_name: 'Parker', last_name: 'Demo', title: 'Operations Lead' },
      { key: 'hr', role: 'HR', email: 'hr@hosspi.com', first_name: 'Quinn', last_name: 'Demo', title: 'HR Officer' },
      { key: 'biomed', role: 'BIOMED', email: 'biomed@hosspi.com', first_name: 'Avery', last_name: 'Demo', title: 'Biomedical Engineer', extra_roles: ['BIOMED_MANAGER'] },
      { key: 'house_keeper', role: 'HOUSE_KEEPER', email: 'housekeeping@hosspi.com', first_name: 'Dakota', last_name: 'Demo', title: 'Housekeeping Supervisor', extra_roles: ['HOUSEKEEPING_MANAGER'] },
      { key: 'ambulance', role: 'AMBULANCE_OPERATOR', email: 'ambulance@hosspi.com', first_name: 'Reese', last_name: 'Demo', title: 'Ambulance Operator' },
      { key: 'paramedic', role: 'PARAMEDIC', email: 'paramedic@hosspi.com', first_name: 'Perry', last_name: 'Demo', title: 'Paramedic' },
      { key: 'emt', role: 'EMT', email: 'emt@hosspi.com', first_name: 'Ellis', last_name: 'Demo', title: 'Emergency Medical Technician' },
      { key: 'physiotherapist', role: 'PHYSIOTHERAPIST', email: 'physio@hosspi.com', first_name: 'Peyton', last_name: 'Demo', title: 'Physiotherapist' },
      { key: 'occupational_therapist', role: 'OCCUPATIONAL_THERAPIST', email: 'ot@hosspi.com', first_name: 'Oakley', last_name: 'Therapy', title: 'Occupational Therapist' },
      { key: 'respiratory_therapist', role: 'RESPIRATORY_THERAPIST', email: 'rt@hosspi.com', first_name: 'River', last_name: 'Demo', title: 'Respiratory Therapist' },
      { key: 'dietitian', role: 'DIETITIAN', email: 'dietitian@hosspi.com', first_name: 'Dana', last_name: 'Demo', title: 'Dietitian' },
      { key: 'social_worker', role: 'SOCIAL_WORKER', email: 'social@hosspi.com', first_name: 'Shawn', last_name: 'Demo', title: 'Medical Social Worker' },
      { key: 'clinical_psychologist', role: 'CLINICAL_PSYCHOLOGIST', email: 'psychologist@hosspi.com', first_name: 'Piper', last_name: 'Demo', title: 'Clinical Psychologist' },
      { key: 'mortuary_staff', role: 'MORTUARY_STAFF', email: 'mortuary.staff@hosspi.com', first_name: 'Taylor', last_name: 'Mortuary', title: 'Mortuary Officer' },
      { key: 'mortuary_manager', role: 'MORTUARY_MANAGER', email: 'mortuary.manager@hosspi.com', first_name: 'Jordan', last_name: 'Mortuary', title: 'Mortuary Manager' },
      { key: 'patient', role: 'PATIENT', email: 'patient.portal@hosspi.com', first_name: 'Patient', last_name: 'Demo', title: 'Patient Portal User' },
    ],
  },
]);

const DEMO_TENANT = DEMO_TENANTS[0];

const CURATED_MODELS = Object.freeze(new Set([
  'tenant',
  'facility',
  'department',
  'ward',
  'room',
  'bed',
  'address',
  'contact',
  'role',
  'permission',
  'role_permission',
  'user',
  'user_profile',
  'user_role',
  'patient',
  'appointment',
  'encounter',
  'diagnosis',
  'vital_sign',
  'admission',
  'lab_test',
  'lab_order',
  'lab_order_item',
  'lab_sample',
  'lab_result',
  'radiology_procedure',
  'radiology_order',
  'radiology_result',
  'drug',
  'pharmacy_order',
  'pharmacy_order_item',
  'dispense_log',
  'inventory_item',
  'inventory_stock',
  'supplier',
  'purchase_request',
  'purchase_order',
  'goods_receipt',
  'emergency_case',
  'triage_assessment',
  'ambulance',
  'ambulance_dispatch',
  'ambulance_trip',
  'invoice',
  'invoice_item',
  'payment',
  'refund',
  'billing_adjustment',
  'staff_position',
  'staff_profile',
  'shift',
  'shift_assignment',
  'roster',
  'housekeeping_task',
  'maintenance_request',
  'equipment_category',
  'equipment_registry',
  'equipment_maintenance_plan',
  'equipment_work_order',
  'equipment_calibration_log',
  'equipment_safety_test_log',
  'equipment_downtime_log',
  'equipment_spare_part',
  'equipment_incident_report',
  'equipment_recall_notice',
  'equipment_utilization_snapshot',
  'equipment_disposal_transfer',
  'unit_management_assignment',
  'mortuary_deceased_profile',
  'mortuary_case',
  'mortuary_storage_unit',
  'mortuary_storage_slot',
  'mortuary_storage_assignment',
  'mortuary_custody_event',
  'mortuary_viewing',
  'mortuary_post_mortem_request',
  'mortuary_release_authorisation',
  'mortuary_billable_event',
  'billable_charge_event',
  'notification',
  'notification_delivery',
  'conversation',
  'message',
  'conversation_participant',
  'conversation_visibility_role',
  'message_attachment',
  'template',
  'template_variable',
  'subscription_plan',
  'subscription',
  'subscription_invoice',
  'module',
  'module_subscription',
  'license',
  'configuration_snapshot',
  'audit_log',
  'phi_access_log',
  'data_processing_log',
  'breach_notification',
  'system_change_log',
  'abac_policy',
  'break_glass_access',
  'break_glass_review',
  'office_context',
  'shift_close',
  'day_close',
  'handover',
  'custody_snapshot',
  'closeout_pack',
  'integration',
  'integration_log',
  'webhook_subscription',
]));

module.exports = {
  CURATED_MODELS,
  DEMO_ADD_ON_CATALOG,
  DEMO_CORE_MODULE_CATALOG,
  DEMO_PLAN_CATALOG,
  DEMO_ROLE_CODES,
  DEMO_TENANT,
  DEMO_TENANTS,
};
