/**
 * Canonical role catalog for HMS access control.
 *
 * Multiple role assignments are supported through `user_role`. These constants
 * define canonical names used by backend authorization, seeds, and frontend
 * alignment.
 */
const ROLES = Object.freeze({
  PLATFORM_OWNER: 'PLATFORM_OWNER',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN',
  FACILITY_ADMIN: 'FACILITY_ADMIN',
  INTEGRATION_ADMIN: 'INTEGRATION_ADMIN',
  HR_STAFF: 'HR_STAFF',
  OPERATIONS_STAFF: 'OPERATIONS_STAFF',
  DISCHARGE_PLANNER: 'DISCHARGE_PLANNER',
  DENTIST: 'DENTIST',
  RADIOLOGIST: 'RADIOLOGIST',
  ACCOUNTANT: 'ACCOUNTANT',
  SUPPORT_STAFF: 'SUPPORT_STAFF',
  VISITOR_GUEST: 'VISITOR_GUEST',
  DOCTOR: 'DOCTOR',
  OPD_DOCTOR: 'OPD_DOCTOR',
  ICU_DOCTOR: 'ICU_DOCTOR',
  NURSE: 'NURSE',
  LAB_TECH: 'LAB_TECH',
  RADIOLOGY_TECH: 'RADIOLOGY_TECH',
  PHARMACIST: 'PHARMACIST',
  PHARMACY_BILLING: 'PHARMACY_BILLING',
  RECEPTIONIST: 'RECEPTIONIST',
  BILLING: 'BILLING',
  FACILITY_BILLING: 'FACILITY_BILLING',
  OPERATIONS: 'OPERATIONS',
  HR: 'HR',
  BIOMED: 'BIOMED',
  HOUSE_KEEPER: 'HOUSE_KEEPER',
  AMBULANCE_OPERATOR: 'AMBULANCE_OPERATOR',
  UNIT_MANAGER: 'UNIT_MANAGER',
  WARD_MANAGER: 'WARD_MANAGER',
  ICU_MANAGER: 'ICU_MANAGER',
  THEATRE_MANAGER: 'THEATRE_MANAGER',
  HOUSEKEEPING_MANAGER: 'HOUSEKEEPING_MANAGER',
  BIOMED_MANAGER: 'BIOMED_MANAGER',
  MORTUARY_STAFF: 'MORTUARY_STAFF',
  MORTUARY_MANAGER: 'MORTUARY_MANAGER',
  ATTENDING_PHYSICIAN: 'ATTENDING_PHYSICIAN',
  RESIDENT_PHYSICIAN: 'RESIDENT_PHYSICIAN',
  SURGEON: 'SURGEON',
  ANESTHESIOLOGIST: 'ANESTHESIOLOGIST',
  PHYSICIAN_ASSISTANT: 'PHYSICIAN_ASSISTANT',
  EMERGENCY_PHYSICIAN: 'EMERGENCY_PHYSICIAN',
  LICENSED_PRACTICAL_NURSE: 'LICENSED_PRACTICAL_NURSE',
  NURSE_PRACTITIONER: 'NURSE_PRACTITIONER',
  TRIAGE_NURSE: 'TRIAGE_NURSE',
  MIDWIFE: 'MIDWIFE',
  CHARGE_NURSE: 'CHARGE_NURSE',
  PHYSIOTHERAPIST: 'PHYSIOTHERAPIST',
  OCCUPATIONAL_THERAPIST: 'OCCUPATIONAL_THERAPIST',
  RESPIRATORY_THERAPIST: 'RESPIRATORY_THERAPIST',
  DIETITIAN: 'DIETITIAN',
  SOCIAL_WORKER: 'SOCIAL_WORKER',
  CLINICAL_PSYCHOLOGIST: 'CLINICAL_PSYCHOLOGIST',
  PATHOLOGIST: 'PATHOLOGIST',
  MEDICAL_LABORATORY_SCIENTIST: 'MEDICAL_LABORATORY_SCIENTIST',
  SONOGRAPHER: 'SONOGRAPHER',
  PHARMACY_TECHNICIAN: 'PHARMACY_TECHNICIAN',
  PARAMEDIC: 'PARAMEDIC',
  EMT: 'EMT',
  MEDICAL_RECORDS_CLERK: 'MEDICAL_RECORDS_CLERK',
  ADMISSIONS_COORDINATOR: 'ADMISSIONS_COORDINATOR',
  MEDICAL_CODER: 'MEDICAL_CODER',
  IT_SUPPORT: 'IT_SUPPORT',
  SECURITY_OFFICER: 'SECURITY_OFFICER',
  CHAPLAIN: 'CHAPLAIN',
  FOOD_SERVICE_WORKER: 'FOOD_SERVICE_WORKER',
  PORTER: 'PORTER',
  MAINTENANCE_ENGINEER: 'MAINTENANCE_ENGINEER',
  PATIENT: 'PATIENT',
  OTHER: 'OTHER'
});

const ROLE_VALUES = Object.freeze(Object.values(ROLES));

const LEGACY_ROLE_ALIASES = Object.freeze({
  ADMIN: ROLES.TENANT_ADMIN,
  ADMINISTRATOR: ROLES.TENANT_ADMIN,
  APP_ADMIN: ROLES.PLATFORM_ADMIN,
  OWNER: ROLES.TENANT_ADMIN,
  SUPERADMIN: ROLES.PLATFORM_ADMIN,
  SUPER_ADMIN: ROLES.PLATFORM_ADMIN,
  SYSTEM_ADMIN: ROLES.PLATFORM_ADMIN,
  FACILITY_MANAGER: ROLES.FACILITY_ADMIN,
  HOSPITAL_ADMIN: ROLES.FACILITY_ADMIN,
  HOSPITAL_MANAGER: ROLES.FACILITY_ADMIN,
  AMBULANCE_DRIVER: ROLES.AMBULANCE_OPERATOR,
  EMT: ROLES.AMBULANCE_OPERATOR,
  PARAMEDIC: ROLES.AMBULANCE_OPERATOR,
  RADIOGRAPHER: ROLES.RADIOLOGY_TECH,
  RADIOLOGY_TECHNICIAN: ROLES.RADIOLOGY_TECH,
  IMAGING_TECH: ROLES.RADIOLOGY_TECH,
  LABORATORY_TECHNICIAN: ROLES.LAB_TECH,
  HOUSEKEEPER: ROLES.HOUSE_KEEPER,
  BIOMEDICAL_ENGINEER: ROLES.BIOMED,
  MORTUARY_ATTENDANT: ROLES.MORTUARY_STAFF,
  WARD_IN_CHARGE: ROLES.WARD_MANAGER,
  CHARGE_NURSE: ROLES.WARD_MANAGER,
  MATRON: ROLES.WARD_MANAGER,
  MORTUARY_OFFICER: ROLES.MORTUARY_STAFF,
  MORGUE_ATTENDANT: ROLES.MORTUARY_STAFF,
  HOUSEKEEPING_SUPERVISOR: ROLES.HOUSEKEEPING_MANAGER,
  RN: ROLES.NURSE,
  REGISTERED_NURSE: ROLES.NURSE,
  LPN: ROLES.LICENSED_PRACTICAL_NURSE,
  NP: ROLES.NURSE_PRACTITIONER,
  PA: ROLES.PHYSICIAN_ASSISTANT,
  ATTENDING: ROLES.ATTENDING_PHYSICIAN,
  RESIDENT: ROLES.RESIDENT_PHYSICIAN,
  MEDICAL_CODER: ROLES.MEDICAL_CODER,
  CODING_SPECIALIST: ROLES.MEDICAL_CODER,
  HIM_OFFICER: ROLES.MEDICAL_RECORDS_CLERK,
  HEALTH_INFORMATION_OFFICER: ROLES.MEDICAL_RECORDS_CLERK,
  PT: ROLES.PHYSIOTHERAPIST,
  OT: ROLES.OCCUPATIONAL_THERAPIST,
  RT: ROLES.RESPIRATORY_THERAPIST,
  MLS: ROLES.MEDICAL_LABORATORY_SCIENTIST,
  USER: ROLES.OTHER,
  GUEST: ROLES.OTHER
});

/**
 * Normalize a role candidate to a canonical catalog value.
 *
 * @param {string | null | undefined} role
 * @returns {string | null}
 */
const normalizeRoleName = (role) => {
  const normalized = String(role || '')
    .trim()
    .toUpperCase()
    .replace(/[\s-]+/g, '_');
  if (!normalized) return null;
  if (LEGACY_ROLE_ALIASES[normalized]) return LEGACY_ROLE_ALIASES[normalized];
  if (ROLE_VALUES.includes(normalized)) return normalized;
  return null;
};

const isCanonicalRole = (role) => normalizeRoleName(role) !== null;

const ELEVATED_ROLES = Object.freeze([
  ROLES.PLATFORM_OWNER,
  ROLES.PLATFORM_ADMIN,
]);
const STAFF_PATIENT_FLOW_DENIED_ROLES = Object.freeze([
  ROLES.PATIENT,
  ROLES.HOUSE_KEEPER,
  ROLES.HOUSEKEEPING_MANAGER,
  ROLES.OTHER
]);

const ROLE_HIERARCHY = Object.freeze({
  [ROLES.OTHER]: 0,
  [ROLES.PATIENT]: 1,
  [ROLES.HOUSE_KEEPER]: 2,
  [ROLES.RECEPTIONIST]: 3,
  [ROLES.BILLING]: 4,
  [ROLES.OPERATIONS]: 5,
  [ROLES.AMBULANCE_OPERATOR]: 6,
  [ROLES.LAB_TECH]: 7,
  [ROLES.RADIOLOGY_TECH]: 8,
  [ROLES.PHARMACIST]: 9,
  [ROLES.BIOMED]: 10,
  [ROLES.MORTUARY_STAFF]: 11,
  [ROLES.NURSE]: 12,
  [ROLES.DOCTOR]: 13,
  [ROLES.HR]: 14,
  [ROLES.UNIT_MANAGER]: 15,
  [ROLES.WARD_MANAGER]: 16,
  [ROLES.ICU_MANAGER]: 17,
  [ROLES.THEATRE_MANAGER]: 18,
  [ROLES.HOUSEKEEPING_MANAGER]: 19,
  [ROLES.BIOMED_MANAGER]: 20,
  [ROLES.MORTUARY_MANAGER]: 21,
  [ROLES.FACILITY_ADMIN]: 22,
  [ROLES.TENANT_ADMIN]: 23,
  [ROLES.PLATFORM_ADMIN]: 24,
  [ROLES.PLATFORM_OWNER]: 25,
});

module.exports = {
  ROLES,
  ROLE_VALUES,
  ROLE_HIERARCHY,
  ELEVATED_ROLES,
  STAFF_PATIENT_FLOW_DENIED_ROLES,
  LEGACY_ROLE_ALIASES,
  normalizeRoleName,
  isCanonicalRole
};
