import 'package:hosspi_hms/features/reports/presentation/domain_reporting_catalogs.dart';
import 'package:hosspi_hms/features/reports/presentation/pharmacy_reporting_labels.dart';
import 'package:hosspi_hms/features/reports/presentation/reports_role_tailoring.dart';
import 'package:hosspi_hms/l10n/app_localizations.dart';
import 'package:hosspi_hms/shared/reporting/reporting.dart';

/// Shared Reporting chrome labels for non-pharmacy domain packs.
///
/// Reuses pharmacy chrome strings that are already generic (Reporting,
/// Analytics, period/export copy) and swaps category titles per pack.
ModuleReportingLabels domainReportingLabels(
  AppLocalizations l10n,
  ReportsDomainPack pack,
) {
  final ModuleReportingLabels pharmacy = pharmacyReportingLabels(l10n);
  return ModuleReportingLabels(
    reportingTabLabel: pharmacy.reportingTabLabel,
    analyticsTabLabel: pharmacy.analyticsTabLabel,
    searchSemanticLabel: 'Search ${reportsDomainPackTitle(pack).toLowerCase()} reports',
    searchHint: pharmacy.searchHint,
    clearSearchLabel: pharmacy.clearSearchLabel,
    filtersActionLabel: pharmacy.filtersActionLabel,
    expandAllAction: pharmacy.expandAllAction,
    collapseAllAction: pharmacy.collapseAllAction,
    catalogEmpty: pharmacy.catalogEmpty,
    categoryFilterLabel: pharmacy.categoryFilterLabel,
    subcategoryFilterLabel: pharmacy.subcategoryFilterLabel,
    contentKindFilterLabel: pharmacy.contentKindFilterLabel,
    contentKindTable: pharmacy.contentKindTable,
    contentKindChart: pharmacy.contentKindChart,
    allLabel: pharmacy.allLabel,
    dateRangeLabel: pharmacy.dateRangeLabel,
    dateFromLabel: pharmacy.dateFromLabel,
    dateToLabel: pharmacy.dateToLabel,
    datePickerLabel: pharmacy.datePickerLabel,
    invalidDateMessage: pharmacy.invalidDateMessage,
    dateFilterHint: pharmacy.dateFilterHint,
    selectCategoryHint: pharmacy.selectCategoryHint,
    clearFiltersAction: pharmacy.clearFiltersAction,
    applyFiltersAction: pharmacy.applyFiltersAction,
    closeAction: pharmacy.closeAction,
    cancelAction: pharmacy.cancelAction,
    advancedFiltersTitle: pharmacy.advancedFiltersTitle,
    categoryTitle: (String categoryId) =>
        reportsDomainCategoryTitle(pack, categoryId),
    periodToday: pharmacy.periodToday,
    periodLastWeek: pharmacy.periodLastWeek,
    periodLastMonth: pharmacy.periodLastMonth,
    periodLast3Months: pharmacy.periodLast3Months,
    periodLast6Months: pharmacy.periodLast6Months,
    periodLast12Months: pharmacy.periodLast12Months,
    periodLast24Months: pharmacy.periodLast24Months,
    periodCustom: pharmacy.periodCustom,
    periodLabel: pharmacy.periodLabel,
    activeRangeSummary: pharmacy.activeRangeSummary,
    customRangeTitle: pharmacy.customRangeTitle,
    customRangeBody: pharmacy.customRangeBody,
    customRangeApplyAction: pharmacy.customRangeApplyAction,
    customRangeRequired: pharmacy.customRangeRequired,
    unavailableTitle: pharmacy.unavailableTitle,
    unavailableBody: pharmacy.unavailableBody,
    unavailableMappedBody: pharmacy.unavailableMappedBody,
    loadingTitle: pharmacy.loadingTitle,
    loadingBody: pharmacy.loadingBody,
    errorTitle: pharmacy.errorTitle,
    errorBody: pharmacy.errorBody,
    emptyTitle: pharmacy.emptyTitle,
    emptyBody: pharmacy.emptyBody,
    retryAction: pharmacy.retryAction,
    printAction: pharmacy.printAction,
    printSubtitle: pharmacy.printSubtitle,
    printFooter: pharmacy.printFooter,
    referenceLabel: pharmacy.referenceLabel,
    previewTitle: pharmacy.previewTitle,
    nameColumnLabel: pharmacy.nameColumnLabel,
    statusColumnLabel: pharmacy.statusColumnLabel,
    exportAction: pharmacy.exportAction,
    exportDialogTitle: pharmacy.exportDialogTitle,
    exportDialogBody: pharmacy.exportDialogBody,
    exportFormatLabel: pharmacy.exportFormatLabel,
    exportExcelAction: pharmacy.exportExcelAction,
    exportExcelOptionBody: pharmacy.exportExcelOptionBody,
    exportPdfAction: pharmacy.exportPdfAction,
    exportPdfOptionBody: pharmacy.exportPdfOptionBody,
    exportPdfSubtitle: pharmacy.exportPdfSubtitle,
    exportFieldColumn: pharmacy.exportFieldColumn,
    exportValueColumn: pharmacy.exportValueColumn,
    exportSheetName: pharmacy.exportSheetName,
    exportNotesLabel: pharmacy.exportNotesLabel,
    exportColumnsSectionLabel: pharmacy.exportColumnsSectionLabel,
    exportFiltersSectionLabel: pharmacy.exportFiltersSectionLabel,
    exportEmptyColumnsMessage: pharmacy.exportEmptyColumnsMessage,
    exportEmptyRowsMessage: pharmacy.exportEmptyRowsMessage,
    exportSuccessMessage: pharmacy.exportSuccessMessage,
    exportFailureMessage: pharmacy.exportFailureMessage,
    unknownValue: pharmacy.unknownValue,
  );
}
