const PDFDocument = require('pdfkit');

const toDecimalNumber = (value) => {
  if (value === null || value === undefined || value === '') return 0;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
};

const money = (value, currency = '') =>
  `${String(currency || '').trim()} ${toDecimalNumber(value).toFixed(2)}`.trim();

const resolvePatientName = (patient = {}) => {
  const firstName = String(patient.first_name || '').trim();
  const lastName = String(patient.last_name || '').trim();
  return `${firstName} ${lastName}`.trim() || 'N/A';
};

const resolveDisplayId = (record = {}) =>
  String(record.display_id || record.human_friendly_id || '').trim() || 'N/A';

const formatDate = (value) => {
  if (!value) return 'N/A';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'N/A';
  return date.toISOString().slice(0, 10);
};

const generateInvoicePdfBuffer = async ({ invoice, financials = {} }) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const invoiceCurrency = String(invoice?.currency || '').trim() || 'USD';
    const patientName = resolvePatientName(invoice?.patient || {});
    const invoiceDisplayId = resolveDisplayId(invoice || {});
    const patientDisplayId = resolveDisplayId(invoice?.patient || {});

    doc.fontSize(20).text('Invoice', { align: 'left' });
    doc.moveDown(0.3);
    doc.fontSize(11).text(`Invoice: ${invoiceDisplayId}`);
    doc.text(`Patient: ${patientName} (${patientDisplayId})`);
    doc.text(`Issued: ${formatDate(invoice?.issued_at || invoice?.created_at)}`);
    doc.text(`Status: ${invoice?.status || 'N/A'}`);
    doc.text(`Billing Status: ${invoice?.billing_status || 'N/A'}`);
    doc.moveDown();

    doc.fontSize(13).text('Items');
    doc.moveDown(0.3);

    const items = Array.isArray(invoice?.items) ? invoice.items : [];
    if (!items.length) {
      doc.fontSize(11).text('No line items.');
    } else {
      items.forEach((item, index) => {
        const description = String(item?.description || '').trim() || `Item ${index + 1}`;
        const quantity = Number.isFinite(Number(item?.quantity)) ? Number(item.quantity) : 1;
        const unitPrice = money(item?.unit_price, invoiceCurrency);
        const totalPrice = money(item?.total_price, invoiceCurrency);

        doc.fontSize(11).text(`${index + 1}. ${description}`);
        doc.fontSize(10).text(`Qty: ${quantity}  Unit: ${unitPrice}  Total: ${totalPrice}`);
        doc.moveDown(0.2);
      });
    }

    doc.moveDown();
    doc.fontSize(13).text('Summary');
    doc.moveDown(0.3);

    const lines = [
      ['Invoice Total', money(financials.invoice_total ?? invoice?.total_amount, invoiceCurrency)],
      ['Adjustments', money(financials.adjustment_total ?? 0, invoiceCurrency)],
      ['Effective Total', money(financials.effective_total ?? invoice?.total_amount, invoiceCurrency)],
      ['Payments', money(financials.gross_paid_total ?? 0, invoiceCurrency)],
      ['Refunds', money(financials.refunded_total ?? 0, invoiceCurrency)],
      ['Net Paid', money(financials.net_paid_total ?? 0, invoiceCurrency)],
      ['Balance Due', money(financials.balance_due ?? invoice?.total_amount, invoiceCurrency)],
    ];

    lines.forEach(([label, value]) => {
      doc.fontSize(11).text(`${label}: ${value}`);
    });

    doc.moveDown();
    doc.fontSize(9).fillColor('#666').text('Generated by HMS Billing Workspace');
    doc.end();
  });

module.exports = {
  generateInvoicePdfBuffer,
};
